// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: trade-grpc.proto

package trade

import (
	denom "github.com/sologenic/com-fs-asset-model/domain/denom"
	com_fs_order_model "github.com/sologenic/com-fs-order-model"
	metadata "github.com/sologenic/com-fs-utils-lib/models/metadata"
	order_properties "github.com/sologenic/com-fs-utils-lib/models/order-properties"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Ability to get all trade history views using the filter options
type Filter struct {
	state          protoimpl.MessageState        `protogen:"open.v1"`
	Network        metadata.Network              `protobuf:"varint,1,opt,name=Network,proto3,enum=metadata.Network" json:"Network,omitempty"`
	From           *timestamppb.Timestamp        `protobuf:"bytes,2,opt,name=From,proto3,oneof" json:"From,omitempty"`
	To             *timestamppb.Timestamp        `protobuf:"bytes,3,opt,name=To,proto3,oneof" json:"To,omitempty"`
	Sequence       *int64                        `protobuf:"varint,4,opt,name=Sequence,proto3,oneof" json:"Sequence,omitempty"`
	OrderKey       *string                       `protobuf:"bytes,5,opt,name=OrderKey,proto3,oneof" json:"OrderKey,omitempty"` // Datastore key
	TXID           *string                       `protobuf:"bytes,6,opt,name=TXID,proto3,oneof" json:"TXID,omitempty"`
	Denom1         *denom.Denom                  `protobuf:"bytes,7,opt,name=Denom1,proto3,oneof" json:"Denom1,omitempty"`
	Denom2         *denom.Denom                  `protobuf:"bytes,8,opt,name=Denom2,proto3,oneof" json:"Denom2,omitempty"`
	Side           *order_properties.Side        `protobuf:"varint,9,opt,name=Side,proto3,enum=orderproperties.Side,oneof" json:"Side,omitempty"`
	OrganizationID string                        `protobuf:"bytes,10,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`
	UserID         *string                       `protobuf:"bytes,11,opt,name=UserID,proto3,oneof" json:"UserID,omitempty"`                                             // User ID for the trade
	TradeType      *com_fs_order_model.TradeType `protobuf:"varint,12,opt,name=TradeType,proto3,enum=order.TradeType,oneof" json:"TradeType,omitempty"`                 // The type of the trade, e.g. limit, market, etc.
	TimeInForce    *order_properties.TimeInForce `protobuf:"varint,13,opt,name=TimeInForce,proto3,enum=orderproperties.TimeInForce,oneof" json:"TimeInForce,omitempty"` // The time in force for the trade, e.g. GTC, IOC, FOK, etc.
	Limit          *int32                        `protobuf:"varint,14,opt,name=Limit,proto3,oneof" json:"Limit,omitempty"`
	// Use for batch queries (with IN operator) instead of Denom1/Denom2
	Denom1Symbols []string      `protobuf:"bytes,15,rep,name=Denom1Symbols,proto3" json:"Denom1Symbols,omitempty"`                              // List of Denom1 symbols to filter trades
	Denom2Symbols []string      `protobuf:"bytes,16,rep,name=Denom2Symbols,proto3" json:"Denom2Symbols,omitempty"`                              // List of Denom2 symbols to filter trades
	ActivityType  *ActivityType `protobuf:"varint,17,opt,name=ActivityType,proto3,enum=trade.ActivityType,oneof" json:"ActivityType,omitempty"` // Type of activity that the order represents, e.g. deposit, withdrawal, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_trade_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_trade_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_trade_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *Filter) GetNetwork() metadata.Network {
	if x != nil {
		return x.Network
	}
	return metadata.Network(0)
}

func (x *Filter) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Filter) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Filter) GetSequence() int64 {
	if x != nil && x.Sequence != nil {
		return *x.Sequence
	}
	return 0
}

func (x *Filter) GetOrderKey() string {
	if x != nil && x.OrderKey != nil {
		return *x.OrderKey
	}
	return ""
}

func (x *Filter) GetTXID() string {
	if x != nil && x.TXID != nil {
		return *x.TXID
	}
	return ""
}

func (x *Filter) GetDenom1() *denom.Denom {
	if x != nil {
		return x.Denom1
	}
	return nil
}

func (x *Filter) GetDenom2() *denom.Denom {
	if x != nil {
		return x.Denom2
	}
	return nil
}

func (x *Filter) GetSide() order_properties.Side {
	if x != nil && x.Side != nil {
		return *x.Side
	}
	return order_properties.Side(0)
}

func (x *Filter) GetOrganizationID() string {
	if x != nil {
		return x.OrganizationID
	}
	return ""
}

func (x *Filter) GetUserID() string {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return ""
}

func (x *Filter) GetTradeType() com_fs_order_model.TradeType {
	if x != nil && x.TradeType != nil {
		return *x.TradeType
	}
	return com_fs_order_model.TradeType(0)
}

func (x *Filter) GetTimeInForce() order_properties.TimeInForce {
	if x != nil && x.TimeInForce != nil {
		return *x.TimeInForce
	}
	return order_properties.TimeInForce(0)
}

func (x *Filter) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *Filter) GetDenom1Symbols() []string {
	if x != nil {
		return x.Denom1Symbols
	}
	return nil
}

func (x *Filter) GetDenom2Symbols() []string {
	if x != nil {
		return x.Denom2Symbols
	}
	return nil
}

func (x *Filter) GetActivityType() ActivityType {
	if x != nil && x.ActivityType != nil {
		return *x.ActivityType
	}
	return ActivityType_NOT_USED_ACTIVITY_TYPE
}

type TradeKey struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TXID           string                 `protobuf:"bytes,1,opt,name=TXID,proto3" json:"TXID,omitempty"` // Transaction hash for the trade
	OrganizationID string                 `protobuf:"bytes,2,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`
	Network        metadata.Network       `protobuf:"varint,3,opt,name=Network,proto3,enum=metadata.Network" json:"Network,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TradeKey) Reset() {
	*x = TradeKey{}
	mi := &file_trade_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeKey) ProtoMessage() {}

func (x *TradeKey) ProtoReflect() protoreflect.Message {
	mi := &file_trade_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeKey.ProtoReflect.Descriptor instead.
func (*TradeKey) Descriptor() ([]byte, []int) {
	return file_trade_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *TradeKey) GetTXID() string {
	if x != nil {
		return x.TXID
	}
	return ""
}

func (x *TradeKey) GetOrganizationID() string {
	if x != nil {
		return x.OrganizationID
	}
	return ""
}

func (x *TradeKey) GetNetwork() metadata.Network {
	if x != nil {
		return x.Network
	}
	return metadata.Network(0)
}

var File_trade_grpc_proto protoreflect.FileDescriptor

const file_trade_grpc_proto_rawDesc = "" +
	"\n" +
	"\x10trade-grpc.proto\x12\x05trade\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1aIsologenic/com-fs-utils-lib/models/order-properties/order-properties.proto\x1a9sologenic/com-fs-utils-lib/models/metadata/metadata.proto\x1a5sologenic/com-fs-asset-model/domain/denom/denom.proto\x1a)sologenic/com-fs-order-model/broker.proto\x1a\vtrade.proto\"\xf6\x06\n" +
	"\x06Filter\x12+\n" +
	"\aNetwork\x18\x01 \x01(\x0e2\x11.metadata.NetworkR\aNetwork\x123\n" +
	"\x04From\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x04From\x88\x01\x01\x12/\n" +
	"\x02To\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x02To\x88\x01\x01\x12\x1f\n" +
	"\bSequence\x18\x04 \x01(\x03H\x02R\bSequence\x88\x01\x01\x12\x1f\n" +
	"\bOrderKey\x18\x05 \x01(\tH\x03R\bOrderKey\x88\x01\x01\x12\x17\n" +
	"\x04TXID\x18\x06 \x01(\tH\x04R\x04TXID\x88\x01\x01\x12)\n" +
	"\x06Denom1\x18\a \x01(\v2\f.denom.DenomH\x05R\x06Denom1\x88\x01\x01\x12)\n" +
	"\x06Denom2\x18\b \x01(\v2\f.denom.DenomH\x06R\x06Denom2\x88\x01\x01\x12.\n" +
	"\x04Side\x18\t \x01(\x0e2\x15.orderproperties.SideH\aR\x04Side\x88\x01\x01\x12&\n" +
	"\x0eOrganizationID\x18\n" +
	" \x01(\tR\x0eOrganizationID\x12\x1b\n" +
	"\x06UserID\x18\v \x01(\tH\bR\x06UserID\x88\x01\x01\x123\n" +
	"\tTradeType\x18\f \x01(\x0e2\x10.order.TradeTypeH\tR\tTradeType\x88\x01\x01\x12C\n" +
	"\vTimeInForce\x18\r \x01(\x0e2\x1c.orderproperties.TimeInForceH\n" +
	"R\vTimeInForce\x88\x01\x01\x12\x19\n" +
	"\x05Limit\x18\x0e \x01(\x05H\vR\x05Limit\x88\x01\x01\x12$\n" +
	"\rDenom1Symbols\x18\x0f \x03(\tR\rDenom1Symbols\x12$\n" +
	"\rDenom2Symbols\x18\x10 \x03(\tR\rDenom2Symbols\x12<\n" +
	"\fActivityType\x18\x11 \x01(\x0e2\x13.trade.ActivityTypeH\fR\fActivityType\x88\x01\x01B\a\n" +
	"\x05_FromB\x05\n" +
	"\x03_ToB\v\n" +
	"\t_SequenceB\v\n" +
	"\t_OrderKeyB\a\n" +
	"\x05_TXIDB\t\n" +
	"\a_Denom1B\t\n" +
	"\a_Denom2B\a\n" +
	"\x05_SideB\t\n" +
	"\a_UserIDB\f\n" +
	"\n" +
	"_TradeTypeB\x0e\n" +
	"\f_TimeInForceB\b\n" +
	"\x06_LimitB\x0f\n" +
	"\r_ActivityType\"s\n" +
	"\bTradeKey\x12\x12\n" +
	"\x04TXID\x18\x01 \x01(\tR\x04TXID\x12&\n" +
	"\x0eOrganizationID\x18\x02 \x01(\tR\x0eOrganizationID\x12+\n" +
	"\aNetwork\x18\x03 \x01(\x0e2\x11.metadata.NetworkR\aNetwork2\xc8\x01\n" +
	"\fTradeService\x12&\n" +
	"\x03Get\x12\x0f.trade.TradeKey\x1a\f.trade.Trade\"\x00\x120\n" +
	"\x06Upsert\x12\f.trade.Trade\x1a\x16.google.protobuf.Empty\"\x00\x126\n" +
	"\vBatchUpsert\x12\r.trade.Trades\x1a\x16.google.protobuf.Empty\"\x00\x12&\n" +
	"\x04List\x12\r.trade.Filter\x1a\r.trade.Trades\"\x00B/Z-github.com/sologenic/com-fs-trade-model;tradeb\x06proto3"

var (
	file_trade_grpc_proto_rawDescOnce sync.Once
	file_trade_grpc_proto_rawDescData []byte
)

func file_trade_grpc_proto_rawDescGZIP() []byte {
	file_trade_grpc_proto_rawDescOnce.Do(func() {
		file_trade_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trade_grpc_proto_rawDesc), len(file_trade_grpc_proto_rawDesc)))
	})
	return file_trade_grpc_proto_rawDescData
}

var file_trade_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_trade_grpc_proto_goTypes = []any{
	(*Filter)(nil),                    // 0: trade.Filter
	(*TradeKey)(nil),                  // 1: trade.TradeKey
	(metadata.Network)(0),             // 2: metadata.Network
	(*timestamppb.Timestamp)(nil),     // 3: google.protobuf.Timestamp
	(*denom.Denom)(nil),               // 4: denom.Denom
	(order_properties.Side)(0),        // 5: orderproperties.Side
	(com_fs_order_model.TradeType)(0), // 6: order.TradeType
	(order_properties.TimeInForce)(0), // 7: orderproperties.TimeInForce
	(ActivityType)(0),                 // 8: trade.ActivityType
	(*Trade)(nil),                     // 9: trade.Trade
	(*Trades)(nil),                    // 10: trade.Trades
	(*emptypb.Empty)(nil),             // 11: google.protobuf.Empty
}
var file_trade_grpc_proto_depIdxs = []int32{
	2,  // 0: trade.Filter.Network:type_name -> metadata.Network
	3,  // 1: trade.Filter.From:type_name -> google.protobuf.Timestamp
	3,  // 2: trade.Filter.To:type_name -> google.protobuf.Timestamp
	4,  // 3: trade.Filter.Denom1:type_name -> denom.Denom
	4,  // 4: trade.Filter.Denom2:type_name -> denom.Denom
	5,  // 5: trade.Filter.Side:type_name -> orderproperties.Side
	6,  // 6: trade.Filter.TradeType:type_name -> order.TradeType
	7,  // 7: trade.Filter.TimeInForce:type_name -> orderproperties.TimeInForce
	8,  // 8: trade.Filter.ActivityType:type_name -> trade.ActivityType
	2,  // 9: trade.TradeKey.Network:type_name -> metadata.Network
	1,  // 10: trade.TradeService.Get:input_type -> trade.TradeKey
	9,  // 11: trade.TradeService.Upsert:input_type -> trade.Trade
	10, // 12: trade.TradeService.BatchUpsert:input_type -> trade.Trades
	0,  // 13: trade.TradeService.List:input_type -> trade.Filter
	9,  // 14: trade.TradeService.Get:output_type -> trade.Trade
	11, // 15: trade.TradeService.Upsert:output_type -> google.protobuf.Empty
	11, // 16: trade.TradeService.BatchUpsert:output_type -> google.protobuf.Empty
	10, // 17: trade.TradeService.List:output_type -> trade.Trades
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_trade_grpc_proto_init() }
func file_trade_grpc_proto_init() {
	if File_trade_grpc_proto != nil {
		return
	}
	file_trade_proto_init()
	file_trade_grpc_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trade_grpc_proto_rawDesc), len(file_trade_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trade_grpc_proto_goTypes,
		DependencyIndexes: file_trade_grpc_proto_depIdxs,
		MessageInfos:      file_trade_grpc_proto_msgTypes,
	}.Build()
	File_trade_grpc_proto = out.File
	file_trade_grpc_proto_goTypes = nil
	file_trade_grpc_proto_depIdxs = nil
}
