// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.1
// source: trade.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";
import { Timestamp } from "./google/protobuf/timestamp";
import { Denom } from "./sologenic/com-fs-asset-model/domain/denom/denom";
import {
  TimeInForce,
  timeInForceFromJSON,
  timeInForceToJSON,
  TradeType,
  tradeTypeFromJSON,
  tradeTypeToJSON,
} from "./sologenic/com-fs-order-model/broker";
import { Decimal } from "./sologenic/com-fs-utils-lib/go/decimal/decimal";
import { MetaData } from "./sologenic/com-fs-utils-lib/models/metadata/metadata";
import { Side, sideFromJSON, sideToJSON } from "./sologenic/com-fs-utils-lib/models/order-properties/order-properties";

export const protobufPackage = "trade";

export enum ActivityType {
  NOT_USED_ACTIVITY_TYPE = 0,
  /** DEPOSIT - Deposit of funds to an account */
  DEPOSIT = 1,
  /** WITHDRAWAL - Withdrawal of funds from an account */
  WITHDRAWAL = 2,
  /** DIVIDEND - Dividend payment to an account */
  DIVIDEND = 3,
  /** INTEREST - Interest payment to an account */
  INTEREST = 4,
  /** RECEIVED - Received funds from another account */
  RECEIVED = 5,
  /** TRANSFER - Transfer of funds between accounts */
  TRANSFER = 6,
  /** SUBSCRIPTION - Subscription to a service or product */
  SUBSCRIPTION = 7,
  UNRECOGNIZED = -1,
}

export function activityTypeFromJSON(object: any): ActivityType {
  switch (object) {
    case 0:
    case "NOT_USED_ACTIVITY_TYPE":
      return ActivityType.NOT_USED_ACTIVITY_TYPE;
    case 1:
    case "DEPOSIT":
      return ActivityType.DEPOSIT;
    case 2:
    case "WITHDRAWAL":
      return ActivityType.WITHDRAWAL;
    case 3:
    case "DIVIDEND":
      return ActivityType.DIVIDEND;
    case 4:
    case "INTEREST":
      return ActivityType.INTEREST;
    case 5:
    case "RECEIVED":
      return ActivityType.RECEIVED;
    case 6:
    case "TRANSFER":
      return ActivityType.TRANSFER;
    case 7:
    case "SUBSCRIPTION":
      return ActivityType.SUBSCRIPTION;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ActivityType.UNRECOGNIZED;
  }
}

export function activityTypeToJSON(object: ActivityType): string {
  switch (object) {
    case ActivityType.NOT_USED_ACTIVITY_TYPE:
      return "NOT_USED_ACTIVITY_TYPE";
    case ActivityType.DEPOSIT:
      return "DEPOSIT";
    case ActivityType.WITHDRAWAL:
      return "WITHDRAWAL";
    case ActivityType.DIVIDEND:
      return "DIVIDEND";
    case ActivityType.INTEREST:
      return "INTEREST";
    case ActivityType.RECEIVED:
      return "RECEIVED";
    case ActivityType.TRANSFER:
      return "TRANSFER";
    case ActivityType.SUBSCRIPTION:
      return "SUBSCRIPTION";
    case ActivityType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum Status {
  NOT_USED_STATUS = 0,
  PARTIALLY_FILLED = 1,
  FILLED = 2,
  CANCELLED = 3,
  PLACED = 4,
  EXPIRED = 5,
  PENDING = 6,
  UNRECOGNIZED = -1,
}

export function statusFromJSON(object: any): Status {
  switch (object) {
    case 0:
    case "NOT_USED_STATUS":
      return Status.NOT_USED_STATUS;
    case 1:
    case "PARTIALLY_FILLED":
      return Status.PARTIALLY_FILLED;
    case 2:
    case "FILLED":
      return Status.FILLED;
    case 3:
    case "CANCELLED":
      return Status.CANCELLED;
    case 4:
    case "PLACED":
      return Status.PLACED;
    case 5:
    case "EXPIRED":
      return Status.EXPIRED;
    case 6:
    case "PENDING":
      return Status.PENDING;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Status.UNRECOGNIZED;
  }
}

export function statusToJSON(object: Status): string {
  switch (object) {
    case Status.NOT_USED_STATUS:
      return "NOT_USED_STATUS";
    case Status.PARTIALLY_FILLED:
      return "PARTIALLY_FILLED";
    case Status.FILLED:
      return "FILLED";
    case Status.CANCELLED:
      return "CANCELLED";
    case Status.PLACED:
      return "PLACED";
    case Status.EXPIRED:
      return "EXPIRED";
    case Status.PENDING:
      return "PENDING";
    case Status.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Key in store is TXID-Sequence-Metadata.Network */
export interface Trade {
  UserID: string;
  /** Datastore key: OrderID-SmartContractAddr-Network */
  OrderKey: string;
  /** The sequence number of the order, assigned by the DEX (guaranteed unique value for the order) */
  Sequence: number;
  Amount: Decimal | undefined;
  Price: number;
  /** Base currency (e.g. suwusdc_1-smartContractAddr) */
  Denom1:
    | Denom
    | undefined;
  /** Asset denom (e.g. suaapl_1-smartContractAddr) */
  Denom2:
    | Denom
    | undefined;
  /** The buy/sell (e.g. did the user place a buy or sell order) */
  Side: Side;
  /** The time the trade was executed in UTC */
  BlockTime: Date | undefined;
  OrganizationID: string;
  /** Standard storage related fields */
  MetaData: MetaData | undefined;
  TXID?: string | undefined;
  BlockHeight: number;
  /** If the trade has been enriched with precision data */
  Enriched: boolean;
  /** Check if trade is processed into the OHLC */
  Processed: boolean;
  /**
   * This status field enables unified indexing in Elasticsearch, allowing the backend to return a single combined dataset of both trades(executed orders) and orders for user trade history,
   * eliminating the need for separate Trade and Order queries on the frontend. Therefore, this field is to be used only when creating indexes in Elasticsearch.
   */
  Status?:
    | Status
    | undefined;
  /** USD representation of the trade values and trading fee (fixed base for easy data comparisson in reports etc), applicable for non-WUSDC based trades, RWAs, etc. */
  USD?:
    | number
    | undefined;
  /** The type of the trade, e.g. limit, market, etc. */
  TradeType: TradeType;
  /** The commission paid to the brokerage */
  Commission?:
    | number
    | undefined;
  /** The time in force for the trade, e.g. GTC, IOC, FOK, etc. */
  TimeInForce: TimeInForce;
  /**
   * Type of activity that the order represents, e.g. deposit, withdrawal, etc.
   * Since wallets hold tokenized assets, inflow activities (e.g. deposits, dividends, received) are treated as "buy" and outflow activities (e.g. withdrawals, transfers) as "sell"
   */
  ActivityType?:
    | ActivityType
    | undefined;
  /**
   * Trades get stored in alphabetical order of the denom pair.
   * Data is "uninverted" on retrieval and
   * this flag only indicates that the denoms as seen in the record are not in the original order
   */
  Inverted: boolean;
}

export interface Trades {
  Trades: Trade[];
  /** Offset for pagination */
  Offset?: number | undefined;
}

function createBaseTrade(): Trade {
  return {
    UserID: "",
    OrderKey: "",
    Sequence: 0,
    Amount: undefined,
    Price: 0,
    Denom1: undefined,
    Denom2: undefined,
    Side: 0,
    BlockTime: undefined,
    OrganizationID: "",
    MetaData: undefined,
    TXID: undefined,
    BlockHeight: 0,
    Enriched: false,
    Processed: false,
    Status: undefined,
    USD: undefined,
    TradeType: 0,
    Commission: undefined,
    TimeInForce: 0,
    ActivityType: undefined,
    Inverted: false,
  };
}

export const Trade = {
  encode(message: Trade, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.UserID !== "") {
      writer.uint32(10).string(message.UserID);
    }
    if (message.OrderKey !== "") {
      writer.uint32(18).string(message.OrderKey);
    }
    if (message.Sequence !== 0) {
      writer.uint32(24).int64(message.Sequence);
    }
    if (message.Amount !== undefined) {
      Decimal.encode(message.Amount, writer.uint32(34).fork()).ldelim();
    }
    if (message.Price !== 0) {
      writer.uint32(41).double(message.Price);
    }
    if (message.Denom1 !== undefined) {
      Denom.encode(message.Denom1, writer.uint32(50).fork()).ldelim();
    }
    if (message.Denom2 !== undefined) {
      Denom.encode(message.Denom2, writer.uint32(58).fork()).ldelim();
    }
    if (message.Side !== 0) {
      writer.uint32(64).int32(message.Side);
    }
    if (message.BlockTime !== undefined) {
      Timestamp.encode(toTimestamp(message.BlockTime), writer.uint32(74).fork()).ldelim();
    }
    if (message.OrganizationID !== "") {
      writer.uint32(82).string(message.OrganizationID);
    }
    if (message.MetaData !== undefined) {
      MetaData.encode(message.MetaData, writer.uint32(242).fork()).ldelim();
    }
    if (message.TXID !== undefined) {
      writer.uint32(250).string(message.TXID);
    }
    if (message.BlockHeight !== 0) {
      writer.uint32(256).int64(message.BlockHeight);
    }
    if (message.Enriched !== false) {
      writer.uint32(264).bool(message.Enriched);
    }
    if (message.Processed !== false) {
      writer.uint32(272).bool(message.Processed);
    }
    if (message.Status !== undefined) {
      writer.uint32(280).int32(message.Status);
    }
    if (message.USD !== undefined) {
      writer.uint32(325).float(message.USD);
    }
    if (message.TradeType !== 0) {
      writer.uint32(328).int32(message.TradeType);
    }
    if (message.Commission !== undefined) {
      writer.uint32(337).double(message.Commission);
    }
    if (message.TimeInForce !== 0) {
      writer.uint32(344).int32(message.TimeInForce);
    }
    if (message.ActivityType !== undefined) {
      writer.uint32(352).int32(message.ActivityType);
    }
    if (message.Inverted !== false) {
      writer.uint32(400).bool(message.Inverted);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Trade {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTrade();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.UserID = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.OrderKey = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.Sequence = longToNumber(reader.int64() as Long);
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.Amount = Decimal.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 41) {
            break;
          }

          message.Price = reader.double();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.Denom1 = Denom.decode(reader, reader.uint32());
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.Denom2 = Denom.decode(reader, reader.uint32());
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.Side = reader.int32() as any;
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.BlockTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
        case 30:
          if (tag !== 242) {
            break;
          }

          message.MetaData = MetaData.decode(reader, reader.uint32());
          continue;
        case 31:
          if (tag !== 250) {
            break;
          }

          message.TXID = reader.string();
          continue;
        case 32:
          if (tag !== 256) {
            break;
          }

          message.BlockHeight = longToNumber(reader.int64() as Long);
          continue;
        case 33:
          if (tag !== 264) {
            break;
          }

          message.Enriched = reader.bool();
          continue;
        case 34:
          if (tag !== 272) {
            break;
          }

          message.Processed = reader.bool();
          continue;
        case 35:
          if (tag !== 280) {
            break;
          }

          message.Status = reader.int32() as any;
          continue;
        case 40:
          if (tag !== 325) {
            break;
          }

          message.USD = reader.float();
          continue;
        case 41:
          if (tag !== 328) {
            break;
          }

          message.TradeType = reader.int32() as any;
          continue;
        case 42:
          if (tag !== 337) {
            break;
          }

          message.Commission = reader.double();
          continue;
        case 43:
          if (tag !== 344) {
            break;
          }

          message.TimeInForce = reader.int32() as any;
          continue;
        case 44:
          if (tag !== 352) {
            break;
          }

          message.ActivityType = reader.int32() as any;
          continue;
        case 50:
          if (tag !== 400) {
            break;
          }

          message.Inverted = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Trade {
    return {
      UserID: isSet(object.UserID) ? globalThis.String(object.UserID) : "",
      OrderKey: isSet(object.OrderKey) ? globalThis.String(object.OrderKey) : "",
      Sequence: isSet(object.Sequence) ? globalThis.Number(object.Sequence) : 0,
      Amount: isSet(object.Amount) ? Decimal.fromJSON(object.Amount) : undefined,
      Price: isSet(object.Price) ? globalThis.Number(object.Price) : 0,
      Denom1: isSet(object.Denom1) ? Denom.fromJSON(object.Denom1) : undefined,
      Denom2: isSet(object.Denom2) ? Denom.fromJSON(object.Denom2) : undefined,
      Side: isSet(object.Side) ? sideFromJSON(object.Side) : 0,
      BlockTime: isSet(object.BlockTime) ? fromJsonTimestamp(object.BlockTime) : undefined,
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : "",
      MetaData: isSet(object.MetaData) ? MetaData.fromJSON(object.MetaData) : undefined,
      TXID: isSet(object.TXID) ? globalThis.String(object.TXID) : undefined,
      BlockHeight: isSet(object.BlockHeight) ? globalThis.Number(object.BlockHeight) : 0,
      Enriched: isSet(object.Enriched) ? globalThis.Boolean(object.Enriched) : false,
      Processed: isSet(object.Processed) ? globalThis.Boolean(object.Processed) : false,
      Status: isSet(object.Status) ? statusFromJSON(object.Status) : undefined,
      USD: isSet(object.USD) ? globalThis.Number(object.USD) : undefined,
      TradeType: isSet(object.TradeType) ? tradeTypeFromJSON(object.TradeType) : 0,
      Commission: isSet(object.Commission) ? globalThis.Number(object.Commission) : undefined,
      TimeInForce: isSet(object.TimeInForce) ? timeInForceFromJSON(object.TimeInForce) : 0,
      ActivityType: isSet(object.ActivityType) ? activityTypeFromJSON(object.ActivityType) : undefined,
      Inverted: isSet(object.Inverted) ? globalThis.Boolean(object.Inverted) : false,
    };
  },

  toJSON(message: Trade): unknown {
    const obj: any = {};
    if (message.UserID !== "") {
      obj.UserID = message.UserID;
    }
    if (message.OrderKey !== "") {
      obj.OrderKey = message.OrderKey;
    }
    if (message.Sequence !== 0) {
      obj.Sequence = Math.round(message.Sequence);
    }
    if (message.Amount !== undefined) {
      obj.Amount = Decimal.toJSON(message.Amount);
    }
    if (message.Price !== 0) {
      obj.Price = message.Price;
    }
    if (message.Denom1 !== undefined) {
      obj.Denom1 = Denom.toJSON(message.Denom1);
    }
    if (message.Denom2 !== undefined) {
      obj.Denom2 = Denom.toJSON(message.Denom2);
    }
    if (message.Side !== 0) {
      obj.Side = sideToJSON(message.Side);
    }
    if (message.BlockTime !== undefined) {
      obj.BlockTime = message.BlockTime.toISOString();
    }
    if (message.OrganizationID !== "") {
      obj.OrganizationID = message.OrganizationID;
    }
    if (message.MetaData !== undefined) {
      obj.MetaData = MetaData.toJSON(message.MetaData);
    }
    if (message.TXID !== undefined) {
      obj.TXID = message.TXID;
    }
    if (message.BlockHeight !== 0) {
      obj.BlockHeight = Math.round(message.BlockHeight);
    }
    if (message.Enriched !== false) {
      obj.Enriched = message.Enriched;
    }
    if (message.Processed !== false) {
      obj.Processed = message.Processed;
    }
    if (message.Status !== undefined) {
      obj.Status = statusToJSON(message.Status);
    }
    if (message.USD !== undefined) {
      obj.USD = message.USD;
    }
    if (message.TradeType !== 0) {
      obj.TradeType = tradeTypeToJSON(message.TradeType);
    }
    if (message.Commission !== undefined) {
      obj.Commission = message.Commission;
    }
    if (message.TimeInForce !== 0) {
      obj.TimeInForce = timeInForceToJSON(message.TimeInForce);
    }
    if (message.ActivityType !== undefined) {
      obj.ActivityType = activityTypeToJSON(message.ActivityType);
    }
    if (message.Inverted !== false) {
      obj.Inverted = message.Inverted;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Trade>, I>>(base?: I): Trade {
    return Trade.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Trade>, I>>(object: I): Trade {
    const message = createBaseTrade();
    message.UserID = object.UserID ?? "";
    message.OrderKey = object.OrderKey ?? "";
    message.Sequence = object.Sequence ?? 0;
    message.Amount = (object.Amount !== undefined && object.Amount !== null)
      ? Decimal.fromPartial(object.Amount)
      : undefined;
    message.Price = object.Price ?? 0;
    message.Denom1 = (object.Denom1 !== undefined && object.Denom1 !== null)
      ? Denom.fromPartial(object.Denom1)
      : undefined;
    message.Denom2 = (object.Denom2 !== undefined && object.Denom2 !== null)
      ? Denom.fromPartial(object.Denom2)
      : undefined;
    message.Side = object.Side ?? 0;
    message.BlockTime = object.BlockTime ?? undefined;
    message.OrganizationID = object.OrganizationID ?? "";
    message.MetaData = (object.MetaData !== undefined && object.MetaData !== null)
      ? MetaData.fromPartial(object.MetaData)
      : undefined;
    message.TXID = object.TXID ?? undefined;
    message.BlockHeight = object.BlockHeight ?? 0;
    message.Enriched = object.Enriched ?? false;
    message.Processed = object.Processed ?? false;
    message.Status = object.Status ?? undefined;
    message.USD = object.USD ?? undefined;
    message.TradeType = object.TradeType ?? 0;
    message.Commission = object.Commission ?? undefined;
    message.TimeInForce = object.TimeInForce ?? 0;
    message.ActivityType = object.ActivityType ?? undefined;
    message.Inverted = object.Inverted ?? false;
    return message;
  },
};

function createBaseTrades(): Trades {
  return { Trades: [], Offset: undefined };
}

export const Trades = {
  encode(message: Trades, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.Trades) {
      Trade.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    if (message.Offset !== undefined) {
      writer.uint32(16).int32(message.Offset);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Trades {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTrades();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Trades.push(Trade.decode(reader, reader.uint32()));
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.Offset = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Trades {
    return {
      Trades: globalThis.Array.isArray(object?.Trades) ? object.Trades.map((e: any) => Trade.fromJSON(e)) : [],
      Offset: isSet(object.Offset) ? globalThis.Number(object.Offset) : undefined,
    };
  },

  toJSON(message: Trades): unknown {
    const obj: any = {};
    if (message.Trades?.length) {
      obj.Trades = message.Trades.map((e) => Trade.toJSON(e));
    }
    if (message.Offset !== undefined) {
      obj.Offset = Math.round(message.Offset);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Trades>, I>>(base?: I): Trades {
    return Trades.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Trades>, I>>(object: I): Trades {
    const message = createBaseTrades();
    message.Trades = object.Trades?.map((e) => Trade.fromPartial(e)) || [];
    message.Offset = object.Offset ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (long.lt(globalThis.Number.MIN_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
