syntax = "proto3";

package trade;

option go_package = "github.com/sologenic/com-fs-trade-model;trade";

import "google/protobuf/empty.proto";
import "sologenic/com-fs-utils-lib/models/metadata/metadata.proto";
import "sologenic/com-fs-asset-model/domain/denom/denom.proto";
import "tradepair.proto";

service TradePairService {
    // TradePair
    rpc Get(ID) returns (TradePair) {}
    rpc List(TradePairFilter) returns (TradePairs) {}
    rpc Upsert(TradePair) returns (google.protobuf.Empty) {}
}

message ID {
    string TXID = 1;
    string OrganizaionID = 2; // Organization ID for the trade
    metadata.Network Network = 3;
}

message TradePairFilter {
    metadata.Network Network = 1;
    optional denom.Denom Denom1 = 2;
    optional denom.Denom Denom2 = 3;
    optional int32 Offset = 4;
    string OrganizationID = 5;
}
