// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: tradepair-grpc.proto

package trade

import (
	denom "github.com/sologenic/com-fs-asset-model/domain/denom"
	metadata "github.com/sologenic/com-fs-utils-lib/models/metadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TradePairFilter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Network        metadata.Network       `protobuf:"varint,1,opt,name=Network,proto3,enum=metadata.Network" json:"Network,omitempty"`
	Denom1         *denom.Denom           `protobuf:"bytes,2,opt,name=Denom1,proto3,oneof" json:"Denom1,omitempty"`
	Denom2         *denom.Denom           `protobuf:"bytes,3,opt,name=Denom2,proto3,oneof" json:"Denom2,omitempty"`
	Offset         *int32                 `protobuf:"varint,4,opt,name=Offset,proto3,oneof" json:"Offset,omitempty"`
	OrganizationID string                 `protobuf:"bytes,5,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TradePairFilter) Reset() {
	*x = TradePairFilter{}
	mi := &file_tradepair_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradePairFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradePairFilter) ProtoMessage() {}

func (x *TradePairFilter) ProtoReflect() protoreflect.Message {
	mi := &file_tradepair_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradePairFilter.ProtoReflect.Descriptor instead.
func (*TradePairFilter) Descriptor() ([]byte, []int) {
	return file_tradepair_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *TradePairFilter) GetNetwork() metadata.Network {
	if x != nil {
		return x.Network
	}
	return metadata.Network(0)
}

func (x *TradePairFilter) GetDenom1() *denom.Denom {
	if x != nil {
		return x.Denom1
	}
	return nil
}

func (x *TradePairFilter) GetDenom2() *denom.Denom {
	if x != nil {
		return x.Denom2
	}
	return nil
}

func (x *TradePairFilter) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *TradePairFilter) GetOrganizationID() string {
	if x != nil {
		return x.OrganizationID
	}
	return ""
}

type TradePairKey struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Symbol1        string                 `protobuf:"bytes,1,opt,name=Symbol1,proto3" json:"Symbol1,omitempty"`
	Symbol2        string                 `protobuf:"bytes,2,opt,name=Symbol2,proto3" json:"Symbol2,omitempty"`
	Issuer         string                 `protobuf:"bytes,3,opt,name=Issuer,proto3" json:"Issuer,omitempty"`
	OrganizationID string                 `protobuf:"bytes,4,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`
	Network        metadata.Network       `protobuf:"varint,5,opt,name=Network,proto3,enum=metadata.Network" json:"Network,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TradePairKey) Reset() {
	*x = TradePairKey{}
	mi := &file_tradepair_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradePairKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradePairKey) ProtoMessage() {}

func (x *TradePairKey) ProtoReflect() protoreflect.Message {
	mi := &file_tradepair_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradePairKey.ProtoReflect.Descriptor instead.
func (*TradePairKey) Descriptor() ([]byte, []int) {
	return file_tradepair_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *TradePairKey) GetSymbol1() string {
	if x != nil {
		return x.Symbol1
	}
	return ""
}

func (x *TradePairKey) GetSymbol2() string {
	if x != nil {
		return x.Symbol2
	}
	return ""
}

func (x *TradePairKey) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *TradePairKey) GetOrganizationID() string {
	if x != nil {
		return x.OrganizationID
	}
	return ""
}

func (x *TradePairKey) GetNetwork() metadata.Network {
	if x != nil {
		return x.Network
	}
	return metadata.Network(0)
}

var File_tradepair_grpc_proto protoreflect.FileDescriptor

const file_tradepair_grpc_proto_rawDesc = "" +
	"\n" +
	"\x14tradepair-grpc.proto\x12\x05trade\x1a\x1bgoogle/protobuf/empty.proto\x1a9sologenic/com-fs-utils-lib/models/metadata/metadata.proto\x1a5sologenic/com-fs-asset-model/domain/denom/denom.proto\x1a\x0ftradepair.proto\"\xfa\x01\n" +
	"\x0fTradePairFilter\x12+\n" +
	"\aNetwork\x18\x01 \x01(\x0e2\x11.metadata.NetworkR\aNetwork\x12)\n" +
	"\x06Denom1\x18\x02 \x01(\v2\f.denom.DenomH\x00R\x06Denom1\x88\x01\x01\x12)\n" +
	"\x06Denom2\x18\x03 \x01(\v2\f.denom.DenomH\x01R\x06Denom2\x88\x01\x01\x12\x1b\n" +
	"\x06Offset\x18\x04 \x01(\x05H\x02R\x06Offset\x88\x01\x01\x12&\n" +
	"\x0eOrganizationID\x18\x05 \x01(\tR\x0eOrganizationIDB\t\n" +
	"\a_Denom1B\t\n" +
	"\a_Denom2B\t\n" +
	"\a_Offset\"\xaf\x01\n" +
	"\fTradePairKey\x12\x18\n" +
	"\aSymbol1\x18\x01 \x01(\tR\aSymbol1\x12\x18\n" +
	"\aSymbol2\x18\x02 \x01(\tR\aSymbol2\x12\x16\n" +
	"\x06Issuer\x18\x03 \x01(\tR\x06Issuer\x12&\n" +
	"\x0eOrganizationID\x18\x04 \x01(\tR\x0eOrganizationID\x12+\n" +
	"\aNetwork\x18\x05 \x01(\x0e2\x11.metadata.NetworkR\aNetwork2\xad\x01\n" +
	"\x10TradePairService\x12.\n" +
	"\x03Get\x12\x13.trade.TradePairKey\x1a\x10.trade.TradePair\"\x00\x123\n" +
	"\x04List\x12\x16.trade.TradePairFilter\x1a\x11.trade.TradePairs\"\x00\x124\n" +
	"\x06Upsert\x12\x10.trade.TradePair\x1a\x16.google.protobuf.Empty\"\x00B/Z-github.com/sologenic/com-fs-trade-model;tradeb\x06proto3"

var (
	file_tradepair_grpc_proto_rawDescOnce sync.Once
	file_tradepair_grpc_proto_rawDescData []byte
)

func file_tradepair_grpc_proto_rawDescGZIP() []byte {
	file_tradepair_grpc_proto_rawDescOnce.Do(func() {
		file_tradepair_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tradepair_grpc_proto_rawDesc), len(file_tradepair_grpc_proto_rawDesc)))
	})
	return file_tradepair_grpc_proto_rawDescData
}

var file_tradepair_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tradepair_grpc_proto_goTypes = []any{
	(*TradePairFilter)(nil), // 0: trade.TradePairFilter
	(*TradePairKey)(nil),    // 1: trade.TradePairKey
	(metadata.Network)(0),   // 2: metadata.Network
	(*denom.Denom)(nil),     // 3: denom.Denom
	(*TradePair)(nil),       // 4: trade.TradePair
	(*TradePairs)(nil),      // 5: trade.TradePairs
	(*emptypb.Empty)(nil),   // 6: google.protobuf.Empty
}
var file_tradepair_grpc_proto_depIdxs = []int32{
	2, // 0: trade.TradePairFilter.Network:type_name -> metadata.Network
	3, // 1: trade.TradePairFilter.Denom1:type_name -> denom.Denom
	3, // 2: trade.TradePairFilter.Denom2:type_name -> denom.Denom
	2, // 3: trade.TradePairKey.Network:type_name -> metadata.Network
	1, // 4: trade.TradePairService.Get:input_type -> trade.TradePairKey
	0, // 5: trade.TradePairService.List:input_type -> trade.TradePairFilter
	4, // 6: trade.TradePairService.Upsert:input_type -> trade.TradePair
	4, // 7: trade.TradePairService.Get:output_type -> trade.TradePair
	5, // 8: trade.TradePairService.List:output_type -> trade.TradePairs
	6, // 9: trade.TradePairService.Upsert:output_type -> google.protobuf.Empty
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tradepair_grpc_proto_init() }
func file_tradepair_grpc_proto_init() {
	if File_tradepair_grpc_proto != nil {
		return
	}
	file_tradepair_proto_init()
	file_tradepair_grpc_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tradepair_grpc_proto_rawDesc), len(file_tradepair_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tradepair_grpc_proto_goTypes,
		DependencyIndexes: file_tradepair_grpc_proto_depIdxs,
		MessageInfos:      file_tradepair_grpc_proto_msgTypes,
	}.Build()
	File_tradepair_grpc_proto = out.File
	file_tradepair_grpc_proto_goTypes = nil
	file_tradepair_grpc_proto_depIdxs = nil
}
