// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: trade.proto

package trade

import (
	denom "github.com/sologenic/com-fs-asset-model/domain/denom"
	com_fs_order_model "github.com/sologenic/com-fs-order-model"
	decimal "github.com/sologenic/com-fs-utils-lib/go/decimal"
	metadata "github.com/sologenic/com-fs-utils-lib/models/metadata"
	order_properties "github.com/sologenic/com-fs-utils-lib/models/order-properties"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActivityType int32

const (
	ActivityType_NOT_USED_ACTIVITY_TYPE ActivityType = 0
	ActivityType_ORDER                  ActivityType = 1 // Order related: buy, sell, cancel
	ActivityType_DEPOSIT                ActivityType = 2 // Deposit of funds to an account
	ActivityType_WITHDRAWAL             ActivityType = 3 // Withdrawal of funds from an account
	ActivityType_DIVIDEND               ActivityType = 4 // Dividend payment to an account
	ActivityType_INTEREST               ActivityType = 5 // Interest payment to an account
	ActivityType_RECEIVED               ActivityType = 6 // Received funds from another account
	ActivityType_SENT                   ActivityType = 7 // Sent funds from this account to another account
	ActivityType_SUBSCRIPTION           ActivityType = 8 // Subscription to a service or product
	ActivityType_USDC_USD_CONVERSION    ActivityType = 9 // Conversion of USDC to USD for deposit/withdrawals
)

// Enum value maps for ActivityType.
var (
	ActivityType_name = map[int32]string{
		0: "NOT_USED_ACTIVITY_TYPE",
		1: "ORDER",
		2: "DEPOSIT",
		3: "WITHDRAWAL",
		4: "DIVIDEND",
		5: "INTEREST",
		6: "RECEIVED",
		7: "SENT",
		8: "SUBSCRIPTION",
		9: "USDC_USD_CONVERSION",
	}
	ActivityType_value = map[string]int32{
		"NOT_USED_ACTIVITY_TYPE": 0,
		"ORDER":                  1,
		"DEPOSIT":                2,
		"WITHDRAWAL":             3,
		"DIVIDEND":               4,
		"INTEREST":               5,
		"RECEIVED":               6,
		"SENT":                   7,
		"SUBSCRIPTION":           8,
		"USDC_USD_CONVERSION":    9,
	}
)

func (x ActivityType) Enum() *ActivityType {
	p := new(ActivityType)
	*p = x
	return p
}

func (x ActivityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivityType) Descriptor() protoreflect.EnumDescriptor {
	return file_trade_proto_enumTypes[0].Descriptor()
}

func (ActivityType) Type() protoreflect.EnumType {
	return &file_trade_proto_enumTypes[0]
}

func (x ActivityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActivityType.Descriptor instead.
func (ActivityType) EnumDescriptor() ([]byte, []int) {
	return file_trade_proto_rawDescGZIP(), []int{0}
}

type ReceiverType int32

const (
	ReceiverType_EMAIL    ReceiverType = 0
	ReceiverType_TX       ReceiverType = 1
	ReceiverType_ETHEREUM ReceiverType = 2
	ReceiverType_SOLANA   ReceiverType = 3
)

// Enum value maps for ReceiverType.
var (
	ReceiverType_name = map[int32]string{
		0: "EMAIL",
		1: "TX",
		2: "ETHEREUM",
		3: "SOLANA",
	}
	ReceiverType_value = map[string]int32{
		"EMAIL":    0,
		"TX":       1,
		"ETHEREUM": 2,
		"SOLANA":   3,
	}
)

func (x ReceiverType) Enum() *ReceiverType {
	p := new(ReceiverType)
	*p = x
	return p
}

func (x ReceiverType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReceiverType) Descriptor() protoreflect.EnumDescriptor {
	return file_trade_proto_enumTypes[1].Descriptor()
}

func (ReceiverType) Type() protoreflect.EnumType {
	return &file_trade_proto_enumTypes[1]
}

func (x ReceiverType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReceiverType.Descriptor instead.
func (ReceiverType) EnumDescriptor() ([]byte, []int) {
	return file_trade_proto_rawDescGZIP(), []int{1}
}

type Status int32

const (
	Status_NOT_USED_STATUS  Status = 0
	Status_PARTIALLY_FILLED Status = 1
	Status_FILLED           Status = 2
	Status_CANCELLED        Status = 3
	Status_PLACED           Status = 4
	Status_EXPIRED          Status = 5
	Status_PENDING          Status = 6
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "NOT_USED_STATUS",
		1: "PARTIALLY_FILLED",
		2: "FILLED",
		3: "CANCELLED",
		4: "PLACED",
		5: "EXPIRED",
		6: "PENDING",
	}
	Status_value = map[string]int32{
		"NOT_USED_STATUS":  0,
		"PARTIALLY_FILLED": 1,
		"FILLED":           2,
		"CANCELLED":        3,
		"PLACED":           4,
		"EXPIRED":          5,
		"PENDING":          6,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_trade_proto_enumTypes[2].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_trade_proto_enumTypes[2]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_trade_proto_rawDescGZIP(), []int{2}
}

// Key in store is TXID-Sequence-Metadata.Network
type Trade struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserID         string                 `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	OrderKey       *string                `protobuf:"bytes,2,opt,name=OrderKey,proto3,oneof" json:"OrderKey,omitempty"`              // Datastore key: OrderID-SmartContractAddr-Network
	Sequence       int64                  `protobuf:"varint,3,opt,name=Sequence,proto3" json:"Sequence,omitempty"`                   // The sequence number of the order, assigned by the DEX (guaranteed unique value for the order)
	Amount         *decimal.Decimal       `protobuf:"bytes,4,opt,name=Amount,proto3" json:"Amount,omitempty"`                        // Last fill quantity from the most recent fill/partial fill event
	Price          float64                `protobuf:"fixed64,5,opt,name=Price,proto3" json:"Price,omitempty"`                        // Last fill price from the most recent fill/partial fill event
	Denom1         *denom.Denom           `protobuf:"bytes,6,opt,name=Denom1,proto3" json:"Denom1,omitempty"`                        // Base currency (e.g. suwusdc_1-smartContractAddr)
	Denom2         *denom.Denom           `protobuf:"bytes,7,opt,name=Denom2,proto3" json:"Denom2,omitempty"`                        // Asset denom (e.g. suaapl_1-smartContractAddr)
	Side           order_properties.Side  `protobuf:"varint,8,opt,name=Side,proto3,enum=orderproperties.Side" json:"Side,omitempty"` // The buy/sell (in the context of transactions, buys are inflow of funds and sells are outflow of funds)
	BlockTime      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=BlockTime,proto3" json:"BlockTime,omitempty"`                  // The time the trade was executed in UTC
	OrganizationID string                 `protobuf:"bytes,10,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`
	Receiver       *Receiver              `protobuf:"bytes,11,opt,name=Receiver,proto3,oneof" json:"Receiver,omitempty"` // The address of the receiver, used for sending of funds. Receiver can also be an email address, tx address or blockchain addres from another blockchain.
	// Standard storage related fields
	MetaData    *metadata.MetaData `protobuf:"bytes,30,opt,name=MetaData,proto3" json:"MetaData,omitempty"`
	TXID        *string            `protobuf:"bytes,31,opt,name=TXID,proto3,oneof" json:"TXID,omitempty"`
	BlockHeight int64              `protobuf:"varint,32,opt,name=BlockHeight,proto3" json:"BlockHeight,omitempty"`
	Enriched    bool               `protobuf:"varint,33,opt,name=Enriched,proto3" json:"Enriched,omitempty"`   // If the trade has been enriched with precision data
	Processed   bool               `protobuf:"varint,34,opt,name=Processed,proto3" json:"Processed,omitempty"` // Check if trade is processed into the OHLC
	// This status field enables unified indexing in Elasticsearch, allowing the backend to return a single combined dataset of both trades(executed orders) and orders for user trade history,
	// eliminating the need for separate Trade and Order queries on the frontend. Therefore, this field is to be used only when creating indexes in Elasticsearch.
	Status *Status `protobuf:"varint,35,opt,name=Status,proto3,enum=trade.Status,oneof" json:"Status,omitempty"`
	// USD representation of the trade values and trading fee (fixed base for easy data comparisson in reports etc), applicable for non-WUSDC based trades, RWAs, etc.
	USD         *float32                        `protobuf:"fixed32,40,opt,name=USD,proto3,oneof" json:"USD,omitempty"`                                       // The USD value of the trade, calculated from the USD value of the currencies and the trading fee.
	TradeType   *com_fs_order_model.TradeType   `protobuf:"varint,41,opt,name=TradeType,proto3,enum=order.TradeType,oneof" json:"TradeType,omitempty"`       // The type of the trade, e.g. limit, market, etc.
	Commission  *float64                        `protobuf:"fixed64,42,opt,name=Commission,proto3,oneof" json:"Commission,omitempty"`                         // The commission paid to the brokerage
	TimeInForce *com_fs_order_model.TimeInForce `protobuf:"varint,43,opt,name=TimeInForce,proto3,enum=order.TimeInForce,oneof" json:"TimeInForce,omitempty"` // The time in force for the trade, e.g. GTC, IOC, FOK, etc.
	// Type of activity that the order represents, e.g. deposit, withdrawal, etc.
	// Since wallets hold tokenized assets, we can treat inflow activities (e.g. deposits, dividends, received) as "buys" and outflow activities (e.g. withdrawals, sent) as "sell"
	ActivityType *ActivityType `protobuf:"varint,44,opt,name=ActivityType,proto3,enum=trade.ActivityType,oneof" json:"ActivityType,omitempty"`
	// Trades get stored in alphabetical order of the denom pair.
	// Data is "uninverted" on retrieval and
	// this flag only indicates that the denoms as seen in the record are not in the original order
	Inverted bool `protobuf:"varint,50,opt,name=Inverted,proto3" json:"Inverted,omitempty"`
	// Order request details - what the user originally requested when placing the order
	RequestedQty *decimal.Decimal `protobuf:"bytes,51,opt,name=RequestedQty,proto3,oneof" json:"RequestedQty,omitempty"` // Original requested order quantity
	LimitPrice   *float64         `protobuf:"fixed64,52,opt,name=LimitPrice,proto3,oneof" json:"LimitPrice,omitempty"`   // Limit price set by the user
	// Actual execution details - cumulative results across all fills
	FilledQty      *decimal.Decimal `protobuf:"bytes,53,opt,name=FilledQty,proto3,oneof" json:"FilledQty,omitempty"`             // Total accumulated quantity filled
	FilledAvgPrice *float64         `protobuf:"fixed64,54,opt,name=FilledAvgPrice,proto3,oneof" json:"FilledAvgPrice,omitempty"` // Average execution price
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_trade_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_trade_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_trade_proto_rawDescGZIP(), []int{0}
}

func (x *Trade) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *Trade) GetOrderKey() string {
	if x != nil && x.OrderKey != nil {
		return *x.OrderKey
	}
	return ""
}

func (x *Trade) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Trade) GetAmount() *decimal.Decimal {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Trade) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Trade) GetDenom1() *denom.Denom {
	if x != nil {
		return x.Denom1
	}
	return nil
}

func (x *Trade) GetDenom2() *denom.Denom {
	if x != nil {
		return x.Denom2
	}
	return nil
}

func (x *Trade) GetSide() order_properties.Side {
	if x != nil {
		return x.Side
	}
	return order_properties.Side(0)
}

func (x *Trade) GetBlockTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BlockTime
	}
	return nil
}

func (x *Trade) GetOrganizationID() string {
	if x != nil {
		return x.OrganizationID
	}
	return ""
}

func (x *Trade) GetReceiver() *Receiver {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *Trade) GetMetaData() *metadata.MetaData {
	if x != nil {
		return x.MetaData
	}
	return nil
}

func (x *Trade) GetTXID() string {
	if x != nil && x.TXID != nil {
		return *x.TXID
	}
	return ""
}

func (x *Trade) GetBlockHeight() int64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *Trade) GetEnriched() bool {
	if x != nil {
		return x.Enriched
	}
	return false
}

func (x *Trade) GetProcessed() bool {
	if x != nil {
		return x.Processed
	}
	return false
}

func (x *Trade) GetStatus() Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return Status_NOT_USED_STATUS
}

func (x *Trade) GetUSD() float32 {
	if x != nil && x.USD != nil {
		return *x.USD
	}
	return 0
}

func (x *Trade) GetTradeType() com_fs_order_model.TradeType {
	if x != nil && x.TradeType != nil {
		return *x.TradeType
	}
	return com_fs_order_model.TradeType(0)
}

func (x *Trade) GetCommission() float64 {
	if x != nil && x.Commission != nil {
		return *x.Commission
	}
	return 0
}

func (x *Trade) GetTimeInForce() com_fs_order_model.TimeInForce {
	if x != nil && x.TimeInForce != nil {
		return *x.TimeInForce
	}
	return com_fs_order_model.TimeInForce(0)
}

func (x *Trade) GetActivityType() ActivityType {
	if x != nil && x.ActivityType != nil {
		return *x.ActivityType
	}
	return ActivityType_NOT_USED_ACTIVITY_TYPE
}

func (x *Trade) GetInverted() bool {
	if x != nil {
		return x.Inverted
	}
	return false
}

func (x *Trade) GetRequestedQty() *decimal.Decimal {
	if x != nil {
		return x.RequestedQty
	}
	return nil
}

func (x *Trade) GetLimitPrice() float64 {
	if x != nil && x.LimitPrice != nil {
		return *x.LimitPrice
	}
	return 0
}

func (x *Trade) GetFilledQty() *decimal.Decimal {
	if x != nil {
		return x.FilledQty
	}
	return nil
}

func (x *Trade) GetFilledAvgPrice() float64 {
	if x != nil && x.FilledAvgPrice != nil {
		return *x.FilledAvgPrice
	}
	return 0
}

type Trades struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trades        []*Trade               `protobuf:"bytes,1,rep,name=Trades,proto3" json:"Trades,omitempty"`
	Offset        *int32                 `protobuf:"varint,2,opt,name=Offset,proto3,oneof" json:"Offset,omitempty"` // Offset for pagination
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trades) Reset() {
	*x = Trades{}
	mi := &file_trade_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trades) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trades) ProtoMessage() {}

func (x *Trades) ProtoReflect() protoreflect.Message {
	mi := &file_trade_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trades.ProtoReflect.Descriptor instead.
func (*Trades) Descriptor() ([]byte, []int) {
	return file_trade_proto_rawDescGZIP(), []int{1}
}

func (x *Trades) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

func (x *Trades) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type Receiver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`                    // The address of the receiver, used for sending of funds.
	Type          ReceiverType           `protobuf:"varint,2,opt,name=Type,proto3,enum=trade.ReceiverType" json:"Type,omitempty"` // The type of the receiver, e.g. email, tx address, blockchain address from another blockchain.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receiver) Reset() {
	*x = Receiver{}
	mi := &file_trade_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receiver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receiver) ProtoMessage() {}

func (x *Receiver) ProtoReflect() protoreflect.Message {
	mi := &file_trade_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receiver.ProtoReflect.Descriptor instead.
func (*Receiver) Descriptor() ([]byte, []int) {
	return file_trade_proto_rawDescGZIP(), []int{2}
}

func (x *Receiver) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Receiver) GetType() ReceiverType {
	if x != nil {
		return x.Type
	}
	return ReceiverType_EMAIL
}

var File_trade_proto protoreflect.FileDescriptor

const file_trade_proto_rawDesc = "" +
	"\n" +
	"\vtrade.proto\x12\x05trade\x1a\x1fgoogle/protobuf/timestamp.proto\x1aIsologenic/com-fs-utils-lib/models/order-properties/order-properties.proto\x1a9sologenic/com-fs-utils-lib/models/metadata/metadata.proto\x1a5sologenic/com-fs-asset-model/domain/denom/denom.proto\x1a3sologenic/com-fs-utils-lib/go/decimal/decimal.proto\x1a)sologenic/com-fs-order-model/broker.proto\x1a'sologenic/com-fs-order-model/util.proto\"\xf5\t\n" +
	"\x05Trade\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\tR\x06UserID\x12\x1f\n" +
	"\bOrderKey\x18\x02 \x01(\tH\x00R\bOrderKey\x88\x01\x01\x12\x1a\n" +
	"\bSequence\x18\x03 \x01(\x03R\bSequence\x12(\n" +
	"\x06Amount\x18\x04 \x01(\v2\x10.decimal.DecimalR\x06Amount\x12\x14\n" +
	"\x05Price\x18\x05 \x01(\x01R\x05Price\x12$\n" +
	"\x06Denom1\x18\x06 \x01(\v2\f.denom.DenomR\x06Denom1\x12$\n" +
	"\x06Denom2\x18\a \x01(\v2\f.denom.DenomR\x06Denom2\x12)\n" +
	"\x04Side\x18\b \x01(\x0e2\x15.orderproperties.SideR\x04Side\x128\n" +
	"\tBlockTime\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tBlockTime\x12&\n" +
	"\x0eOrganizationID\x18\n" +
	" \x01(\tR\x0eOrganizationID\x120\n" +
	"\bReceiver\x18\v \x01(\v2\x0f.trade.ReceiverH\x01R\bReceiver\x88\x01\x01\x12.\n" +
	"\bMetaData\x18\x1e \x01(\v2\x12.metadata.MetaDataR\bMetaData\x12\x17\n" +
	"\x04TXID\x18\x1f \x01(\tH\x02R\x04TXID\x88\x01\x01\x12 \n" +
	"\vBlockHeight\x18  \x01(\x03R\vBlockHeight\x12\x1a\n" +
	"\bEnriched\x18! \x01(\bR\bEnriched\x12\x1c\n" +
	"\tProcessed\x18\" \x01(\bR\tProcessed\x12*\n" +
	"\x06Status\x18# \x01(\x0e2\r.trade.StatusH\x03R\x06Status\x88\x01\x01\x12\x15\n" +
	"\x03USD\x18( \x01(\x02H\x04R\x03USD\x88\x01\x01\x123\n" +
	"\tTradeType\x18) \x01(\x0e2\x10.order.TradeTypeH\x05R\tTradeType\x88\x01\x01\x12#\n" +
	"\n" +
	"Commission\x18* \x01(\x01H\x06R\n" +
	"Commission\x88\x01\x01\x129\n" +
	"\vTimeInForce\x18+ \x01(\x0e2\x12.order.TimeInForceH\aR\vTimeInForce\x88\x01\x01\x12<\n" +
	"\fActivityType\x18, \x01(\x0e2\x13.trade.ActivityTypeH\bR\fActivityType\x88\x01\x01\x12\x1a\n" +
	"\bInverted\x182 \x01(\bR\bInverted\x129\n" +
	"\fRequestedQty\x183 \x01(\v2\x10.decimal.DecimalH\tR\fRequestedQty\x88\x01\x01\x12#\n" +
	"\n" +
	"LimitPrice\x184 \x01(\x01H\n" +
	"R\n" +
	"LimitPrice\x88\x01\x01\x123\n" +
	"\tFilledQty\x185 \x01(\v2\x10.decimal.DecimalH\vR\tFilledQty\x88\x01\x01\x12+\n" +
	"\x0eFilledAvgPrice\x186 \x01(\x01H\fR\x0eFilledAvgPrice\x88\x01\x01B\v\n" +
	"\t_OrderKeyB\v\n" +
	"\t_ReceiverB\a\n" +
	"\x05_TXIDB\t\n" +
	"\a_StatusB\x06\n" +
	"\x04_USDB\f\n" +
	"\n" +
	"_TradeTypeB\r\n" +
	"\v_CommissionB\x0e\n" +
	"\f_TimeInForceB\x0f\n" +
	"\r_ActivityTypeB\x0f\n" +
	"\r_RequestedQtyB\r\n" +
	"\v_LimitPriceB\f\n" +
	"\n" +
	"_FilledQtyB\x11\n" +
	"\x0f_FilledAvgPrice\"V\n" +
	"\x06Trades\x12$\n" +
	"\x06Trades\x18\x01 \x03(\v2\f.trade.TradeR\x06Trades\x12\x1b\n" +
	"\x06Offset\x18\x02 \x01(\x05H\x00R\x06Offset\x88\x01\x01B\t\n" +
	"\a_Offset\"M\n" +
	"\bReceiver\x12\x18\n" +
	"\aAddress\x18\x01 \x01(\tR\aAddress\x12'\n" +
	"\x04Type\x18\x02 \x01(\x0e2\x13.trade.ReceiverTypeR\x04Type*\xb1\x01\n" +
	"\fActivityType\x12\x1a\n" +
	"\x16NOT_USED_ACTIVITY_TYPE\x10\x00\x12\t\n" +
	"\x05ORDER\x10\x01\x12\v\n" +
	"\aDEPOSIT\x10\x02\x12\x0e\n" +
	"\n" +
	"WITHDRAWAL\x10\x03\x12\f\n" +
	"\bDIVIDEND\x10\x04\x12\f\n" +
	"\bINTEREST\x10\x05\x12\f\n" +
	"\bRECEIVED\x10\x06\x12\b\n" +
	"\x04SENT\x10\a\x12\x10\n" +
	"\fSUBSCRIPTION\x10\b\x12\x17\n" +
	"\x13USDC_USD_CONVERSION\x10\t*;\n" +
	"\fReceiverType\x12\t\n" +
	"\x05EMAIL\x10\x00\x12\x06\n" +
	"\x02TX\x10\x01\x12\f\n" +
	"\bETHEREUM\x10\x02\x12\n" +
	"\n" +
	"\x06SOLANA\x10\x03*t\n" +
	"\x06Status\x12\x13\n" +
	"\x0fNOT_USED_STATUS\x10\x00\x12\x14\n" +
	"\x10PARTIALLY_FILLED\x10\x01\x12\n" +
	"\n" +
	"\x06FILLED\x10\x02\x12\r\n" +
	"\tCANCELLED\x10\x03\x12\n" +
	"\n" +
	"\x06PLACED\x10\x04\x12\v\n" +
	"\aEXPIRED\x10\x05\x12\v\n" +
	"\aPENDING\x10\x06B/Z-github.com/sologenic/com-fs-trade-model;tradeb\x06proto3"

var (
	file_trade_proto_rawDescOnce sync.Once
	file_trade_proto_rawDescData []byte
)

func file_trade_proto_rawDescGZIP() []byte {
	file_trade_proto_rawDescOnce.Do(func() {
		file_trade_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trade_proto_rawDesc), len(file_trade_proto_rawDesc)))
	})
	return file_trade_proto_rawDescData
}

var file_trade_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_trade_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_trade_proto_goTypes = []any{
	(ActivityType)(0),                   // 0: trade.ActivityType
	(ReceiverType)(0),                   // 1: trade.ReceiverType
	(Status)(0),                         // 2: trade.Status
	(*Trade)(nil),                       // 3: trade.Trade
	(*Trades)(nil),                      // 4: trade.Trades
	(*Receiver)(nil),                    // 5: trade.Receiver
	(*decimal.Decimal)(nil),             // 6: decimal.Decimal
	(*denom.Denom)(nil),                 // 7: denom.Denom
	(order_properties.Side)(0),          // 8: orderproperties.Side
	(*timestamppb.Timestamp)(nil),       // 9: google.protobuf.Timestamp
	(*metadata.MetaData)(nil),           // 10: metadata.MetaData
	(com_fs_order_model.TradeType)(0),   // 11: order.TradeType
	(com_fs_order_model.TimeInForce)(0), // 12: order.TimeInForce
}
var file_trade_proto_depIdxs = []int32{
	6,  // 0: trade.Trade.Amount:type_name -> decimal.Decimal
	7,  // 1: trade.Trade.Denom1:type_name -> denom.Denom
	7,  // 2: trade.Trade.Denom2:type_name -> denom.Denom
	8,  // 3: trade.Trade.Side:type_name -> orderproperties.Side
	9,  // 4: trade.Trade.BlockTime:type_name -> google.protobuf.Timestamp
	5,  // 5: trade.Trade.Receiver:type_name -> trade.Receiver
	10, // 6: trade.Trade.MetaData:type_name -> metadata.MetaData
	2,  // 7: trade.Trade.Status:type_name -> trade.Status
	11, // 8: trade.Trade.TradeType:type_name -> order.TradeType
	12, // 9: trade.Trade.TimeInForce:type_name -> order.TimeInForce
	0,  // 10: trade.Trade.ActivityType:type_name -> trade.ActivityType
	6,  // 11: trade.Trade.RequestedQty:type_name -> decimal.Decimal
	6,  // 12: trade.Trade.FilledQty:type_name -> decimal.Decimal
	3,  // 13: trade.Trades.Trades:type_name -> trade.Trade
	1,  // 14: trade.Receiver.Type:type_name -> trade.ReceiverType
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_trade_proto_init() }
func file_trade_proto_init() {
	if File_trade_proto != nil {
		return
	}
	file_trade_proto_msgTypes[0].OneofWrappers = []any{}
	file_trade_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trade_proto_rawDesc), len(file_trade_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trade_proto_goTypes,
		DependencyIndexes: file_trade_proto_depIdxs,
		EnumInfos:         file_trade_proto_enumTypes,
		MessageInfos:      file_trade_proto_msgTypes,
	}.Build()
	File_trade_proto = out.File
	file_trade_proto_goTypes = nil
	file_trade_proto_depIdxs = nil
}
