// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: trade.proto

package trade

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	decimal "google.golang.org/genproto/googleapis/type/decimal"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TradeSide defines the direction of the trade.
type TradeSide int32

const (
	TradeSide_TRADE_SIDE_UNSPECIFIED TradeSide = 0
	TradeSide_TRADE_SIDE_BUY         TradeSide = 1
	TradeSide_TRADE_SIDE_SELL        TradeSide = 2
)

// Enum value maps for TradeSide.
var (
	TradeSide_name = map[int32]string{
		0: "TRADE_SIDE_UNSPECIFIED",
		1: "TRADE_SIDE_BUY",
		2: "TRADE_SIDE_SELL",
	}
	TradeSide_value = map[string]int32{
		"TRADE_SIDE_UNSPECIFIED": 0,
		"TRADE_SIDE_BUY":         1,
		"TRADE_SIDE_SELL":        2,
	}
)

func (x TradeSide) Enum() *TradeSide {
	p := new(TradeSide)
	*p = x
	return p
}

func (x TradeSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TradeSide) Descriptor() protoreflect.EnumDescriptor {
	return file_trade_proto_enumTypes[0].Descriptor()
}

func (TradeSide) Type() protoreflect.EnumType {
	return &file_trade_proto_enumTypes[0]
}

func (x TradeSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TradeSide.Descriptor instead.
func (TradeSide) EnumDescriptor() ([]byte, []int) {
	return file_trade_proto_rawDescGZIP(), []int{0}
}

// Each trade represents a full or partial fill of an order.
// An order can have zero, one, or many trades.
// We store the exact time when the trade was executed, linked order ID, and fee information.
//
// The Trade model is universal and supports both:
// 1) Broker Securities Smart Contract (buying and selling securities using Alpaca).
// 2) TX marketplace (to be implemented).
//
// A Trade is immutable after it has been saved in the database.
// Datastore Key format: OrganizationID + "_" + ExecutionID
//
// BaseAssetReference, QuoteAssetReference, FeeAssetReference
// These fields specify the assets involved in the trade and can be one of the following:
//
//  1. Asset denom in the TX marketplace (includes subunit, version, issuer address).
//     Example: "uamc_v1-testcore1vrp9245tzfe6quac0ld9qwqe6x747exwgfg0lqglg6vh23jg3vrsmpm3rr" (AMC stock)
//
//  2. Ticker symbol for Alpaca fiat.
//     In Alpaca, trading is done only against USD. Since the user's USD is stored
//     at the broker, we use "USD" as the QuoteAssetReference.
//
// Note: Validation requires the value to be either a strict TX asset denom format or exactly "USD".
type Trade struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique trade execution ID. Uniqueness is guaranteed only within the scope of an organization.
	// This corresponds to the "execution_id" from Alpaca SSE Trade Events.
	// Example: "bf286435-d55d-4fd1-be1e-c9a5b6722c28".
	ExecutionID string `protobuf:"bytes,1,opt,name=ExecutionID,proto3" json:"ExecutionID,omitempty"`
	// Organization UUID.
	OrganizationID string `protobuf:"bytes,2,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`
	// User ID in our system (Firebase UID).
	UserID string `protobuf:"bytes,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
	// Optional external user ID (e.g., the account ID at Alpaca).
	ExternalUserID string `protobuf:"bytes,4,opt,name=ExternalUserID,proto3" json:"ExternalUserID,omitempty"`
	// Internal Order ID.
	// For organizations using the Broker Securities Smart Contract, this is a combination of
	// the user ID and an order sequence.
	// Example: "Sardr0i479afuVl0nRUkthHnUA33_37".
	OrderID string `protobuf:"bytes,5,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	// External Order ID.
	// Used to keep track of orders in third-party services (e.g., the order ID at Alpaca).
	ExternalOrderID string `protobuf:"bytes,6,opt,name=ExternalOrderID,proto3" json:"ExternalOrderID,omitempty"`
	// The direction of the trade (buy or sell).
	Side TradeSide `protobuf:"varint,7,opt,name=Side,proto3,enum=trade.TradeSide" json:"Side,omitempty"`
	// The primary asset being traded.
	// Must be either a valid TX denom or "USD".
	BaseAssetReference string `protobuf:"bytes,8,opt,name=BaseAssetReference,proto3" json:"BaseAssetReference,omitempty"`
	// The asset used to pay for the trade.
	// Must be either a valid TX denom or "USD".
	QuoteAssetReference string `protobuf:"bytes,9,opt,name=QuoteAssetReference,proto3" json:"QuoteAssetReference,omitempty"`
	// Execution price per 1 unit of base, expressed in quote.
	// Must be strictly greater than 0.
	Price *decimal.Decimal `protobuf:"bytes,10,opt,name=Price,proto3" json:"Price,omitempty"`
	// The amount of base that was traded.
	// Must be strictly greater than 0.
	Qty *decimal.Decimal `protobuf:"bytes,11,opt,name=Qty,proto3" json:"Qty,omitempty"`
	// The absolute fee amount paid for this trade execution.
	// Must be greater than or equal to 0.
	FeeQty *decimal.Decimal `protobuf:"bytes,12,opt,name=FeeQty,proto3" json:"FeeQty,omitempty"`
	// The asset in which the fee was paid.
	// Must be either a valid TX denom or "USD".
	FeeAssetReference string `protobuf:"bytes,13,opt,name=FeeAssetReference,proto3" json:"FeeAssetReference,omitempty"`
	// The exact time the trade was executed.
	// This field is required.
	ExecutedAt    *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=ExecutedAt,proto3" json:"ExecutedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_trade_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_trade_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_trade_proto_rawDescGZIP(), []int{0}
}

func (x *Trade) GetExecutionID() string {
	if x != nil {
		return x.ExecutionID
	}
	return ""
}

func (x *Trade) GetOrganizationID() string {
	if x != nil {
		return x.OrganizationID
	}
	return ""
}

func (x *Trade) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *Trade) GetExternalUserID() string {
	if x != nil {
		return x.ExternalUserID
	}
	return ""
}

func (x *Trade) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *Trade) GetExternalOrderID() string {
	if x != nil {
		return x.ExternalOrderID
	}
	return ""
}

func (x *Trade) GetSide() TradeSide {
	if x != nil {
		return x.Side
	}
	return TradeSide_TRADE_SIDE_UNSPECIFIED
}

func (x *Trade) GetBaseAssetReference() string {
	if x != nil {
		return x.BaseAssetReference
	}
	return ""
}

func (x *Trade) GetQuoteAssetReference() string {
	if x != nil {
		return x.QuoteAssetReference
	}
	return ""
}

func (x *Trade) GetPrice() *decimal.Decimal {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *Trade) GetQty() *decimal.Decimal {
	if x != nil {
		return x.Qty
	}
	return nil
}

func (x *Trade) GetFeeQty() *decimal.Decimal {
	if x != nil {
		return x.FeeQty
	}
	return nil
}

func (x *Trade) GetFeeAssetReference() string {
	if x != nil {
		return x.FeeAssetReference
	}
	return ""
}

func (x *Trade) GetExecutedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecutedAt
	}
	return nil
}

// Pagination should be done using From and To timestamps.
type Trades struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trades        []*Trade               `protobuf:"bytes,1,rep,name=Trades,proto3" json:"Trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trades) Reset() {
	*x = Trades{}
	mi := &file_trade_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trades) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trades) ProtoMessage() {}

func (x *Trades) ProtoReflect() protoreflect.Message {
	mi := &file_trade_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trades.ProtoReflect.Descriptor instead.
func (*Trades) Descriptor() ([]byte, []int) {
	return file_trade_proto_rawDescGZIP(), []int{1}
}

func (x *Trades) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

var File_trade_proto protoreflect.FileDescriptor

const file_trade_proto_rawDesc = "" +
	"\n" +
	"\vtrade.proto\x12\x05trade\x1a\x1fgoogle/protobuf/timestamp.proto\x1a&dependencies/google/type/decimal.proto\x1a(dependencies/buf/validate/validate.proto\"\xdf\n" +
	"\n" +
	"\x05Trade\x12>\n" +
	"\vExecutionID\x18\x01 \x01(\tB\x1c\xbaH\x19r\x17\x10 \x18\x80\x012\x10^[a-zA-Z0-9-_]+$R\vExecutionID\x120\n" +
	"\x0eOrganizationID\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x0eOrganizationID\x122\n" +
	"\x06UserID\x18\x03 \x01(\tB\x1a\xbaH\x17r\x15\x10\x1c\x18\x80\x012\x0e^[a-zA-Z0-9]+$R\x06UserID\x12F\n" +
	"\x0eExternalUserID\x18\x04 \x01(\tB\x1e\xbaH\x1b\xd8\x01\x01r\x16\x10\x1c\x18\x80\x012\x0f^[a-zA-Z0-9-]+$R\x0eExternalUserID\x126\n" +
	"\aOrderID\x18\x05 \x01(\tB\x1c\xbaH\x19r\x17\x10\x1e\x18\x80\x012\x10^[a-zA-Z0-9-_]+$R\aOrderID\x12I\n" +
	"\x0fExternalOrderID\x18\x06 \x01(\tB\x1f\xbaH\x1c\xd8\x01\x01r\x17\x10\n" +
	"\x18\x80\x012\x10^[a-zA-Z0-9-_]+$R\x0fExternalOrderID\x120\n" +
	"\x04Side\x18\a \x01(\x0e2\x10.trade.TradeSideB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x04Side\x12\x9d\x01\n" +
	"\x12BaseAssetReference\x18\b \x01(\tBm\xbaHjrh\x10\x012d^(u[-A-Za-z0-9.]+_v[1-9][0-9]{0,2}-(?:test)?core1(?:[02-9ac-hj-np-z]{38}|[02-9ac-hj-np-z]{58})|USD)$R\x12BaseAssetReference\x12\x9f\x01\n" +
	"\x13QuoteAssetReference\x18\t \x01(\tBm\xbaHjrh\x10\x012d^(u[-A-Za-z0-9.]+_v[1-9][0-9]{0,2}-(?:test)?core1(?:[02-9ac-hj-np-z]{38}|[02-9ac-hj-np-z]{58})|USD)$R\x13QuoteAssetReference\x12|\n" +
	"\x05Price\x18\n" +
	" \x01(\v2\x14.google.type.DecimalBP\xbaHM\xba\x01G\n" +
	"\rprice_gt_zero\x12\x1cPrice must be greater than 0\x1a\x18double(this.value) > 0.0\xc8\x01\x01R\x05Price\x12y\n" +
	"\x03Qty\x18\v \x01(\v2\x14.google.type.DecimalBQ\xbaHN\xba\x01H\n" +
	"\vqty_gt_zero\x12\x1fQuantity must be greater than 0\x1a\x18double(this.value) > 0.0\xc8\x01\x01R\x03Qty\x12\x95\x01\n" +
	"\x06FeeQty\x18\f \x01(\v2\x14.google.type.DecimalBg\xbaHd\xba\x01^\n" +
	"\x10fee_qty_gte_zero\x12/Fee quantity must be greater than or equal to 0\x1a\x19double(this.value) >= 0.0\xc8\x01\x01R\x06FeeQty\x12\x9b\x01\n" +
	"\x11FeeAssetReference\x18\r \x01(\tBm\xbaHjrh\x10\x012d^(u[-A-Za-z0-9.]+_v[1-9][0-9]{0,2}-(?:test)?core1(?:[02-9ac-hj-np-z]{38}|[02-9ac-hj-np-z]{58})|USD)$R\x11FeeAssetReference\x12B\n" +
	"\n" +
	"ExecutedAt\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"ExecutedAt\".\n" +
	"\x06Trades\x12$\n" +
	"\x06Trades\x18\x01 \x03(\v2\f.trade.TradeR\x06Trades*P\n" +
	"\tTradeSide\x12\x1a\n" +
	"\x16TRADE_SIDE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eTRADE_SIDE_BUY\x10\x01\x12\x13\n" +
	"\x0fTRADE_SIDE_SELL\x10\x02B/Z-github.com/sologenic/com-fs-trade-model;tradeb\x06proto3"

var (
	file_trade_proto_rawDescOnce sync.Once
	file_trade_proto_rawDescData []byte
)

func file_trade_proto_rawDescGZIP() []byte {
	file_trade_proto_rawDescOnce.Do(func() {
		file_trade_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trade_proto_rawDesc), len(file_trade_proto_rawDesc)))
	})
	return file_trade_proto_rawDescData
}

var file_trade_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_trade_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_trade_proto_goTypes = []any{
	(TradeSide)(0),                // 0: trade.TradeSide
	(*Trade)(nil),                 // 1: trade.Trade
	(*Trades)(nil),                // 2: trade.Trades
	(*decimal.Decimal)(nil),       // 3: google.type.Decimal
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_trade_proto_depIdxs = []int32{
	0, // 0: trade.Trade.Side:type_name -> trade.TradeSide
	3, // 1: trade.Trade.Price:type_name -> google.type.Decimal
	3, // 2: trade.Trade.Qty:type_name -> google.type.Decimal
	3, // 3: trade.Trade.FeeQty:type_name -> google.type.Decimal
	4, // 4: trade.Trade.ExecutedAt:type_name -> google.protobuf.Timestamp
	1, // 5: trade.Trades.Trades:type_name -> trade.Trade
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_trade_proto_init() }
func file_trade_proto_init() {
	if File_trade_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trade_proto_rawDesc), len(file_trade_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trade_proto_goTypes,
		DependencyIndexes: file_trade_proto_depIdxs,
		EnumInfos:         file_trade_proto_enumTypes,
		MessageInfos:      file_trade_proto_msgTypes,
	}.Build()
	File_trade_proto = out.File
	file_trade_proto_goTypes = nil
	file_trade_proto_depIdxs = nil
}
