syntax = "proto3";

package trade;

option go_package = "github.com/sologenic/com-fs-trade-model;trade";

import "sologenic/com-fs-utils-lib/models/metadata/metadata.proto";
import "sologenic/com-fs-asset-model/domain/denom/denom.proto";
import "sologenic/com-fs-utils-lib/models/decimal/decimal.proto";

message TradePair {
    denom.Denom Denom1 = 1;
    denom.Denom Denom2 = 2;
    metadata.MetaData MetaData = 3;
    optional decimal.Decimal PriceTick = 4; 
    optional int64 QuantityStep = 5;
    string OrganizationID = 6;
}

message TradePairs {
    repeated TradePair TradePairs = 1;
    optional int32 Offset = 2;
}