syntax = "proto3";

package trade;

option go_package = "github.com/sologenic/com-fs-trade-model;trade";

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "sologenic/com-fs-utils-lib/models/order-properties/order-properties.proto";
import "sologenic/com-fs-utils-lib/models/metadata/metadata.proto";
import "sologenic/com-fs-asset-model/domain/denom/denom.proto";
import "sologenic/com-fs-order-model/broker.proto";
import "trade.proto";

service TradeService {
    rpc Get(TradeKey) returns (Trade) {}
    rpc Upsert(Trade) returns (google.protobuf.Empty) {}
    rpc BatchUpsert(Trades) returns (google.protobuf.Empty) {}
    rpc List(Filter) returns (Trades) {}
}

// Ability to get all trade history views using the filter options
message Filter {
    metadata.Network Network = 1;
    optional google.protobuf.Timestamp From = 2;
    optional google.protobuf.Timestamp To = 3;
    optional int64 Sequence = 4;
    optional string OrderKey = 5; // Datastore key
    optional string TXID = 6;
    optional denom.Denom Denom1 = 7;
    optional denom.Denom Denom2 = 8;
    optional int32 Offset = 9;
    optional orderproperties.Side Side = 10;
    string OrganizationID = 11;
    optional string UserID = 12; // User ID for the trade
    optional order.TradeType TradeType = 13; // The type of the trade, e.g. limit, market, etc.
    optional order.TimeInForce TimeInForce = 14; // The time in force for the trade, e.g. GTC, IOC, FOK, etc.
    optional int32 Limit = 15; // Limit for pagination
}

message TradeKey {
    string TXID = 1; // Transaction hash for the trade
    string OrganizationID = 2;
    metadata.Network Network = 3;
}
