// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: tradepair-grpc.proto

package trade

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TradePairService_Get_FullMethodName    = "/trade.TradePairService/Get"
	TradePairService_List_FullMethodName   = "/trade.TradePairService/List"
	TradePairService_Upsert_FullMethodName = "/trade.TradePairService/Upsert"
)

// TradePairServiceClient is the client API for TradePairService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TradePairServiceClient interface {
	// TradePair
	Get(ctx context.Context, in *TradePairKey, opts ...grpc.CallOption) (*TradePair, error)
	List(ctx context.Context, in *TradePairFilter, opts ...grpc.CallOption) (*TradePairs, error)
	Upsert(ctx context.Context, in *TradePair, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type tradePairServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTradePairServiceClient(cc grpc.ClientConnInterface) TradePairServiceClient {
	return &tradePairServiceClient{cc}
}

func (c *tradePairServiceClient) Get(ctx context.Context, in *TradePairKey, opts ...grpc.CallOption) (*TradePair, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradePair)
	err := c.cc.Invoke(ctx, TradePairService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradePairServiceClient) List(ctx context.Context, in *TradePairFilter, opts ...grpc.CallOption) (*TradePairs, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradePairs)
	err := c.cc.Invoke(ctx, TradePairService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradePairServiceClient) Upsert(ctx context.Context, in *TradePair, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TradePairService_Upsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradePairServiceServer is the server API for TradePairService service.
// All implementations should embed UnimplementedTradePairServiceServer
// for forward compatibility.
type TradePairServiceServer interface {
	// TradePair
	Get(context.Context, *TradePairKey) (*TradePair, error)
	List(context.Context, *TradePairFilter) (*TradePairs, error)
	Upsert(context.Context, *TradePair) (*emptypb.Empty, error)
}

// UnimplementedTradePairServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTradePairServiceServer struct{}

func (UnimplementedTradePairServiceServer) Get(context.Context, *TradePairKey) (*TradePair, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedTradePairServiceServer) List(context.Context, *TradePairFilter) (*TradePairs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedTradePairServiceServer) Upsert(context.Context, *TradePair) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedTradePairServiceServer) testEmbeddedByValue() {}

// UnsafeTradePairServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradePairServiceServer will
// result in compilation errors.
type UnsafeTradePairServiceServer interface {
	mustEmbedUnimplementedTradePairServiceServer()
}

func RegisterTradePairServiceServer(s grpc.ServiceRegistrar, srv TradePairServiceServer) {
	// If the following call pancis, it indicates UnimplementedTradePairServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TradePairService_ServiceDesc, srv)
}

func _TradePairService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradePairKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradePairServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradePairService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradePairServiceServer).Get(ctx, req.(*TradePairKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradePairService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradePairFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradePairServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradePairService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradePairServiceServer).List(ctx, req.(*TradePairFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradePairService_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradePair)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradePairServiceServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradePairService_Upsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradePairServiceServer).Upsert(ctx, req.(*TradePair))
	}
	return interceptor(ctx, in, info, handler)
}

// TradePairService_ServiceDesc is the grpc.ServiceDesc for TradePairService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TradePairService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trade.TradePairService",
	HandlerType: (*TradePairServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _TradePairService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _TradePairService_List_Handler,
		},
		{
			MethodName: "Upsert",
			Handler:    _TradePairService_Upsert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tradepair-grpc.proto",
}
