// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.1
// source: tradepair.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";
import { Denom } from "./sologenic/com-fs-asset-model/domain/denom/denom";
import { Decimal } from "./sologenic/com-fs-utils-lib/go/decimal/decimal";
import { MetaData } from "./sologenic/com-fs-utils-lib/models/metadata/metadata";

export const protobufPackage = "trade";

export interface TradePair {
  Denom1: Denom | undefined;
  Denom2: Denom | undefined;
  MetaData: MetaData | undefined;
  PriceTick?: Decimal | undefined;
  QuantityStep?: number | undefined;
  OrganizationID: string;
}

export interface TradePairs {
  TradePairs: TradePair[];
  Offset?: number | undefined;
}

function createBaseTradePair(): TradePair {
  return {
    Denom1: undefined,
    Denom2: undefined,
    MetaData: undefined,
    PriceTick: undefined,
    QuantityStep: undefined,
    OrganizationID: "",
  };
}

export const TradePair = {
  encode(message: TradePair, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Denom1 !== undefined) {
      Denom.encode(message.Denom1, writer.uint32(10).fork()).ldelim();
    }
    if (message.Denom2 !== undefined) {
      Denom.encode(message.Denom2, writer.uint32(18).fork()).ldelim();
    }
    if (message.MetaData !== undefined) {
      MetaData.encode(message.MetaData, writer.uint32(26).fork()).ldelim();
    }
    if (message.PriceTick !== undefined) {
      Decimal.encode(message.PriceTick, writer.uint32(34).fork()).ldelim();
    }
    if (message.QuantityStep !== undefined) {
      writer.uint32(40).int64(message.QuantityStep);
    }
    if (message.OrganizationID !== "") {
      writer.uint32(50).string(message.OrganizationID);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TradePair {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTradePair();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Denom1 = Denom.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Denom2 = Denom.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.MetaData = MetaData.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.PriceTick = Decimal.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.QuantityStep = longToNumber(reader.int64() as Long);
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TradePair {
    return {
      Denom1: isSet(object.Denom1) ? Denom.fromJSON(object.Denom1) : undefined,
      Denom2: isSet(object.Denom2) ? Denom.fromJSON(object.Denom2) : undefined,
      MetaData: isSet(object.MetaData) ? MetaData.fromJSON(object.MetaData) : undefined,
      PriceTick: isSet(object.PriceTick) ? Decimal.fromJSON(object.PriceTick) : undefined,
      QuantityStep: isSet(object.QuantityStep) ? globalThis.Number(object.QuantityStep) : undefined,
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : "",
    };
  },

  toJSON(message: TradePair): unknown {
    const obj: any = {};
    if (message.Denom1 !== undefined) {
      obj.Denom1 = Denom.toJSON(message.Denom1);
    }
    if (message.Denom2 !== undefined) {
      obj.Denom2 = Denom.toJSON(message.Denom2);
    }
    if (message.MetaData !== undefined) {
      obj.MetaData = MetaData.toJSON(message.MetaData);
    }
    if (message.PriceTick !== undefined) {
      obj.PriceTick = Decimal.toJSON(message.PriceTick);
    }
    if (message.QuantityStep !== undefined) {
      obj.QuantityStep = Math.round(message.QuantityStep);
    }
    if (message.OrganizationID !== "") {
      obj.OrganizationID = message.OrganizationID;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TradePair>, I>>(base?: I): TradePair {
    return TradePair.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TradePair>, I>>(object: I): TradePair {
    const message = createBaseTradePair();
    message.Denom1 = (object.Denom1 !== undefined && object.Denom1 !== null)
      ? Denom.fromPartial(object.Denom1)
      : undefined;
    message.Denom2 = (object.Denom2 !== undefined && object.Denom2 !== null)
      ? Denom.fromPartial(object.Denom2)
      : undefined;
    message.MetaData = (object.MetaData !== undefined && object.MetaData !== null)
      ? MetaData.fromPartial(object.MetaData)
      : undefined;
    message.PriceTick = (object.PriceTick !== undefined && object.PriceTick !== null)
      ? Decimal.fromPartial(object.PriceTick)
      : undefined;
    message.QuantityStep = object.QuantityStep ?? undefined;
    message.OrganizationID = object.OrganizationID ?? "";
    return message;
  },
};

function createBaseTradePairs(): TradePairs {
  return { TradePairs: [], Offset: undefined };
}

export const TradePairs = {
  encode(message: TradePairs, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.TradePairs) {
      TradePair.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    if (message.Offset !== undefined) {
      writer.uint32(16).int32(message.Offset);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TradePairs {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTradePairs();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.TradePairs.push(TradePair.decode(reader, reader.uint32()));
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.Offset = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TradePairs {
    return {
      TradePairs: globalThis.Array.isArray(object?.TradePairs)
        ? object.TradePairs.map((e: any) => TradePair.fromJSON(e))
        : [],
      Offset: isSet(object.Offset) ? globalThis.Number(object.Offset) : undefined,
    };
  },

  toJSON(message: TradePairs): unknown {
    const obj: any = {};
    if (message.TradePairs?.length) {
      obj.TradePairs = message.TradePairs.map((e) => TradePair.toJSON(e));
    }
    if (message.Offset !== undefined) {
      obj.Offset = Math.round(message.Offset);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TradePairs>, I>>(base?: I): TradePairs {
    return TradePairs.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TradePairs>, I>>(object: I): TradePairs {
    const message = createBaseTradePairs();
    message.TradePairs = object.TradePairs?.map((e) => TradePair.fromPartial(e)) || [];
    message.Offset = object.Offset ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (long.lt(globalThis.Number.MIN_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
