// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: tradepair.proto

package trade

import (
	denom "github.com/sologenic/com-fs-asset-model/domain/denom"
	decimal "github.com/sologenic/com-fs-utils-lib/models/decimal"
	metadata "github.com/sologenic/com-fs-utils-lib/models/metadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TradePair struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Denom1         *denom.Denom           `protobuf:"bytes,1,opt,name=Denom1,proto3" json:"Denom1,omitempty"`
	Denom2         *denom.Denom           `protobuf:"bytes,2,opt,name=Denom2,proto3" json:"Denom2,omitempty"`
	MetaData       *metadata.MetaData     `protobuf:"bytes,3,opt,name=MetaData,proto3" json:"MetaData,omitempty"`
	PriceTick      *decimal.Decimal       `protobuf:"bytes,4,opt,name=PriceTick,proto3,oneof" json:"PriceTick,omitempty"`
	QuantityStep   *int64                 `protobuf:"varint,5,opt,name=QuantityStep,proto3,oneof" json:"QuantityStep,omitempty"`
	OrganizationID string                 `protobuf:"bytes,6,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TradePair) Reset() {
	*x = TradePair{}
	mi := &file_tradepair_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradePair) ProtoMessage() {}

func (x *TradePair) ProtoReflect() protoreflect.Message {
	mi := &file_tradepair_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradePair.ProtoReflect.Descriptor instead.
func (*TradePair) Descriptor() ([]byte, []int) {
	return file_tradepair_proto_rawDescGZIP(), []int{0}
}

func (x *TradePair) GetDenom1() *denom.Denom {
	if x != nil {
		return x.Denom1
	}
	return nil
}

func (x *TradePair) GetDenom2() *denom.Denom {
	if x != nil {
		return x.Denom2
	}
	return nil
}

func (x *TradePair) GetMetaData() *metadata.MetaData {
	if x != nil {
		return x.MetaData
	}
	return nil
}

func (x *TradePair) GetPriceTick() *decimal.Decimal {
	if x != nil {
		return x.PriceTick
	}
	return nil
}

func (x *TradePair) GetQuantityStep() int64 {
	if x != nil && x.QuantityStep != nil {
		return *x.QuantityStep
	}
	return 0
}

func (x *TradePair) GetOrganizationID() string {
	if x != nil {
		return x.OrganizationID
	}
	return ""
}

type TradePairs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradePairs    []*TradePair           `protobuf:"bytes,1,rep,name=TradePairs,proto3" json:"TradePairs,omitempty"`
	Offset        *int32                 `protobuf:"varint,2,opt,name=Offset,proto3,oneof" json:"Offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradePairs) Reset() {
	*x = TradePairs{}
	mi := &file_tradepair_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradePairs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradePairs) ProtoMessage() {}

func (x *TradePairs) ProtoReflect() protoreflect.Message {
	mi := &file_tradepair_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradePairs.ProtoReflect.Descriptor instead.
func (*TradePairs) Descriptor() ([]byte, []int) {
	return file_tradepair_proto_rawDescGZIP(), []int{1}
}

func (x *TradePairs) GetTradePairs() []*TradePair {
	if x != nil {
		return x.TradePairs
	}
	return nil
}

func (x *TradePairs) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

var File_tradepair_proto protoreflect.FileDescriptor

const file_tradepair_proto_rawDesc = "" +
	"\n" +
	"\x0ftradepair.proto\x12\x05trade\x1a9sologenic/com-fs-utils-lib/models/metadata/metadata.proto\x1a5sologenic/com-fs-asset-model/domain/denom/denom.proto\x1a7sologenic/com-fs-utils-lib/models/decimal/decimal.proto\"\xac\x02\n" +
	"\tTradePair\x12$\n" +
	"\x06Denom1\x18\x01 \x01(\v2\f.denom.DenomR\x06Denom1\x12$\n" +
	"\x06Denom2\x18\x02 \x01(\v2\f.denom.DenomR\x06Denom2\x12.\n" +
	"\bMetaData\x18\x03 \x01(\v2\x12.metadata.MetaDataR\bMetaData\x123\n" +
	"\tPriceTick\x18\x04 \x01(\v2\x10.decimal.DecimalH\x00R\tPriceTick\x88\x01\x01\x12'\n" +
	"\fQuantityStep\x18\x05 \x01(\x03H\x01R\fQuantityStep\x88\x01\x01\x12&\n" +
	"\x0eOrganizationID\x18\x06 \x01(\tR\x0eOrganizationIDB\f\n" +
	"\n" +
	"_PriceTickB\x0f\n" +
	"\r_QuantityStep\"f\n" +
	"\n" +
	"TradePairs\x120\n" +
	"\n" +
	"TradePairs\x18\x01 \x03(\v2\x10.trade.TradePairR\n" +
	"TradePairs\x12\x1b\n" +
	"\x06Offset\x18\x02 \x01(\x05H\x00R\x06Offset\x88\x01\x01B\t\n" +
	"\a_OffsetB/Z-github.com/sologenic/com-fs-trade-model;tradeb\x06proto3"

var (
	file_tradepair_proto_rawDescOnce sync.Once
	file_tradepair_proto_rawDescData []byte
)

func file_tradepair_proto_rawDescGZIP() []byte {
	file_tradepair_proto_rawDescOnce.Do(func() {
		file_tradepair_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tradepair_proto_rawDesc), len(file_tradepair_proto_rawDesc)))
	})
	return file_tradepair_proto_rawDescData
}

var file_tradepair_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tradepair_proto_goTypes = []any{
	(*TradePair)(nil),         // 0: trade.TradePair
	(*TradePairs)(nil),        // 1: trade.TradePairs
	(*denom.Denom)(nil),       // 2: denom.Denom
	(*metadata.MetaData)(nil), // 3: metadata.MetaData
	(*decimal.Decimal)(nil),   // 4: decimal.Decimal
}
var file_tradepair_proto_depIdxs = []int32{
	2, // 0: trade.TradePair.Denom1:type_name -> denom.Denom
	2, // 1: trade.TradePair.Denom2:type_name -> denom.Denom
	3, // 2: trade.TradePair.MetaData:type_name -> metadata.MetaData
	4, // 3: trade.TradePair.PriceTick:type_name -> decimal.Decimal
	0, // 4: trade.TradePairs.TradePairs:type_name -> trade.TradePair
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_tradepair_proto_init() }
func file_tradepair_proto_init() {
	if File_tradepair_proto != nil {
		return
	}
	file_tradepair_proto_msgTypes[0].OneofWrappers = []any{}
	file_tradepair_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tradepair_proto_rawDesc), len(file_tradepair_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tradepair_proto_goTypes,
		DependencyIndexes: file_tradepair_proto_depIdxs,
		MessageInfos:      file_tradepair_proto_msgTypes,
	}.Build()
	File_tradepair_proto = out.File
	file_tradepair_proto_goTypes = nil
	file_tradepair_proto_depIdxs = nil
}
