// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v7.35.1
// source: trade.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { Decimal } from "./dependencies/google/type/decimal";
import { Timestamp } from "./google/protobuf/timestamp";

export const protobufPackage = "trade";

/** TradeSide defines the direction of the trade. */
export enum TradeSide {
  TRADE_SIDE_UNSPECIFIED = 0,
  TRADE_SIDE_BUY = 1,
  TRADE_SIDE_SELL = 2,
  UNRECOGNIZED = -1,
}

export function tradeSideFromJSON(object: any): TradeSide {
  switch (object) {
    case 0:
    case "TRADE_SIDE_UNSPECIFIED":
      return TradeSide.TRADE_SIDE_UNSPECIFIED;
    case 1:
    case "TRADE_SIDE_BUY":
      return TradeSide.TRADE_SIDE_BUY;
    case 2:
    case "TRADE_SIDE_SELL":
      return TradeSide.TRADE_SIDE_SELL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TradeSide.UNRECOGNIZED;
  }
}

export function tradeSideToJSON(object: TradeSide): string {
  switch (object) {
    case TradeSide.TRADE_SIDE_UNSPECIFIED:
      return "TRADE_SIDE_UNSPECIFIED";
    case TradeSide.TRADE_SIDE_BUY:
      return "TRADE_SIDE_BUY";
    case TradeSide.TRADE_SIDE_SELL:
      return "TRADE_SIDE_SELL";
    case TradeSide.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * Each trade represents a full or partial fill of an order.
 * An order can have zero, one, or many trades.
 * We store the exact time when the trade was executed, linked order ID, and fee information.
 *
 * The Trade model is universal and supports both:
 * 1) Broker Securities Smart Contract (buying and selling securities using Alpaca).
 * 2) TX marketplace (to be implemented).
 *
 * A Trade is immutable after it has been saved in the database.
 * Datastore Key format: OrganizationID + "_" + ExecutionID
 *
 * BaseAssetReference, QuoteAssetReference, FeeAssetReference
 * These fields specify the assets involved in the trade and can be one of the following:
 *
 * 1) Asset denom in the TX marketplace (includes subunit, version, issuer address).
 *    Example: "uamc_v1-testcore1vrp9245tzfe6quac0ld9qwqe6x747exwgfg0lqglg6vh23jg3vrsmpm3rr" (AMC stock)
 *
 * 2) Ticker symbol for Alpaca fiat.
 *    In Alpaca, trading is done only against USD. Since the user's USD is stored
 *    at the broker, we use "USD" as the QuoteAssetReference.
 *
 * Note: Validation requires the value to be either a strict TX asset denom format or exactly "USD".
 */
export interface Trade {
  /**
   * Unique trade execution ID. Uniqueness is guaranteed only within the scope of an organization.
   * This corresponds to the "execution_id" from Alpaca SSE Trade Events.
   * Example: "bf286435-d55d-4fd1-be1e-c9a5b6722c28".
   */
  ExecutionID: string;
  /** Organization UUID. */
  OrganizationID: string;
  /** User ID in our system (Firebase UID). */
  UserID: string;
  /** Optional external user ID (e.g., the account ID at Alpaca). */
  ExternalUserID: string;
  /**
   * Internal Order ID.
   * For organizations using the Broker Securities Smart Contract, this is a combination of
   * the user ID and an order sequence.
   * Example: "Sardr0i479afuVl0nRUkthHnUA33_37".
   */
  OrderID: string;
  /**
   * External Order ID.
   * Used to keep track of orders in third-party services (e.g., the order ID at Alpaca).
   */
  ExternalOrderID: string;
  /** The direction of the trade (buy or sell). */
  Side: TradeSide;
  /**
   * The primary asset being traded.
   * Must be either a valid TX denom or "USD".
   */
  BaseAssetReference: string;
  /**
   * The asset used to pay for the trade.
   * Must be either a valid TX denom or "USD".
   */
  QuoteAssetReference: string;
  /**
   * Execution price per 1 unit of base, expressed in quote.
   * Must be strictly greater than 0.
   */
  Price:
    | Decimal
    | undefined;
  /**
   * The amount of base that was traded.
   * Must be strictly greater than 0.
   */
  Qty:
    | Decimal
    | undefined;
  /**
   * The absolute fee amount paid for this trade execution.
   * Must be greater than or equal to 0.
   */
  FeeQty:
    | Decimal
    | undefined;
  /**
   * The asset in which the fee was paid.
   * Must be either a valid TX denom or "USD".
   */
  FeeAssetReference: string;
  /**
   * The exact time the trade was executed.
   * This field is required.
   */
  ExecutedAt: Date | undefined;
}

/** Pagination should be done using From and To timestamps. */
export interface Trades {
  Trades: Trade[];
}

function createBaseTrade(): Trade {
  return {
    ExecutionID: "",
    OrganizationID: "",
    UserID: "",
    ExternalUserID: "",
    OrderID: "",
    ExternalOrderID: "",
    Side: 0,
    BaseAssetReference: "",
    QuoteAssetReference: "",
    Price: undefined,
    Qty: undefined,
    FeeQty: undefined,
    FeeAssetReference: "",
    ExecutedAt: undefined,
  };
}

export const Trade = {
  encode(message: Trade, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.ExecutionID !== "") {
      writer.uint32(10).string(message.ExecutionID);
    }
    if (message.OrganizationID !== "") {
      writer.uint32(18).string(message.OrganizationID);
    }
    if (message.UserID !== "") {
      writer.uint32(26).string(message.UserID);
    }
    if (message.ExternalUserID !== "") {
      writer.uint32(34).string(message.ExternalUserID);
    }
    if (message.OrderID !== "") {
      writer.uint32(42).string(message.OrderID);
    }
    if (message.ExternalOrderID !== "") {
      writer.uint32(50).string(message.ExternalOrderID);
    }
    if (message.Side !== 0) {
      writer.uint32(56).int32(message.Side);
    }
    if (message.BaseAssetReference !== "") {
      writer.uint32(66).string(message.BaseAssetReference);
    }
    if (message.QuoteAssetReference !== "") {
      writer.uint32(74).string(message.QuoteAssetReference);
    }
    if (message.Price !== undefined) {
      Decimal.encode(message.Price, writer.uint32(82).fork()).ldelim();
    }
    if (message.Qty !== undefined) {
      Decimal.encode(message.Qty, writer.uint32(90).fork()).ldelim();
    }
    if (message.FeeQty !== undefined) {
      Decimal.encode(message.FeeQty, writer.uint32(98).fork()).ldelim();
    }
    if (message.FeeAssetReference !== "") {
      writer.uint32(106).string(message.FeeAssetReference);
    }
    if (message.ExecutedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.ExecutedAt), writer.uint32(114).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Trade {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTrade();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.ExecutionID = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.UserID = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.ExternalUserID = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.OrderID = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.ExternalOrderID = reader.string();
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.Side = reader.int32() as any;
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.BaseAssetReference = reader.string();
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.QuoteAssetReference = reader.string();
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.Price = Decimal.decode(reader, reader.uint32());
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.Qty = Decimal.decode(reader, reader.uint32());
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.FeeQty = Decimal.decode(reader, reader.uint32());
          continue;
        case 13:
          if (tag !== 106) {
            break;
          }

          message.FeeAssetReference = reader.string();
          continue;
        case 14:
          if (tag !== 114) {
            break;
          }

          message.ExecutedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Trade {
    return {
      ExecutionID: isSet(object.ExecutionID) ? globalThis.String(object.ExecutionID) : "",
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : "",
      UserID: isSet(object.UserID) ? globalThis.String(object.UserID) : "",
      ExternalUserID: isSet(object.ExternalUserID) ? globalThis.String(object.ExternalUserID) : "",
      OrderID: isSet(object.OrderID) ? globalThis.String(object.OrderID) : "",
      ExternalOrderID: isSet(object.ExternalOrderID) ? globalThis.String(object.ExternalOrderID) : "",
      Side: isSet(object.Side) ? tradeSideFromJSON(object.Side) : 0,
      BaseAssetReference: isSet(object.BaseAssetReference) ? globalThis.String(object.BaseAssetReference) : "",
      QuoteAssetReference: isSet(object.QuoteAssetReference) ? globalThis.String(object.QuoteAssetReference) : "",
      Price: isSet(object.Price) ? Decimal.fromJSON(object.Price) : undefined,
      Qty: isSet(object.Qty) ? Decimal.fromJSON(object.Qty) : undefined,
      FeeQty: isSet(object.FeeQty) ? Decimal.fromJSON(object.FeeQty) : undefined,
      FeeAssetReference: isSet(object.FeeAssetReference) ? globalThis.String(object.FeeAssetReference) : "",
      ExecutedAt: isSet(object.ExecutedAt) ? fromJsonTimestamp(object.ExecutedAt) : undefined,
    };
  },

  toJSON(message: Trade): unknown {
    const obj: any = {};
    if (message.ExecutionID !== "") {
      obj.ExecutionID = message.ExecutionID;
    }
    if (message.OrganizationID !== "") {
      obj.OrganizationID = message.OrganizationID;
    }
    if (message.UserID !== "") {
      obj.UserID = message.UserID;
    }
    if (message.ExternalUserID !== "") {
      obj.ExternalUserID = message.ExternalUserID;
    }
    if (message.OrderID !== "") {
      obj.OrderID = message.OrderID;
    }
    if (message.ExternalOrderID !== "") {
      obj.ExternalOrderID = message.ExternalOrderID;
    }
    if (message.Side !== 0) {
      obj.Side = tradeSideToJSON(message.Side);
    }
    if (message.BaseAssetReference !== "") {
      obj.BaseAssetReference = message.BaseAssetReference;
    }
    if (message.QuoteAssetReference !== "") {
      obj.QuoteAssetReference = message.QuoteAssetReference;
    }
    if (message.Price !== undefined) {
      obj.Price = Decimal.toJSON(message.Price);
    }
    if (message.Qty !== undefined) {
      obj.Qty = Decimal.toJSON(message.Qty);
    }
    if (message.FeeQty !== undefined) {
      obj.FeeQty = Decimal.toJSON(message.FeeQty);
    }
    if (message.FeeAssetReference !== "") {
      obj.FeeAssetReference = message.FeeAssetReference;
    }
    if (message.ExecutedAt !== undefined) {
      obj.ExecutedAt = message.ExecutedAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Trade>, I>>(base?: I): Trade {
    return Trade.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Trade>, I>>(object: I): Trade {
    const message = createBaseTrade();
    message.ExecutionID = object.ExecutionID ?? "";
    message.OrganizationID = object.OrganizationID ?? "";
    message.UserID = object.UserID ?? "";
    message.ExternalUserID = object.ExternalUserID ?? "";
    message.OrderID = object.OrderID ?? "";
    message.ExternalOrderID = object.ExternalOrderID ?? "";
    message.Side = object.Side ?? 0;
    message.BaseAssetReference = object.BaseAssetReference ?? "";
    message.QuoteAssetReference = object.QuoteAssetReference ?? "";
    message.Price = (object.Price !== undefined && object.Price !== null)
      ? Decimal.fromPartial(object.Price)
      : undefined;
    message.Qty = (object.Qty !== undefined && object.Qty !== null) ? Decimal.fromPartial(object.Qty) : undefined;
    message.FeeQty = (object.FeeQty !== undefined && object.FeeQty !== null)
      ? Decimal.fromPartial(object.FeeQty)
      : undefined;
    message.FeeAssetReference = object.FeeAssetReference ?? "";
    message.ExecutedAt = object.ExecutedAt ?? undefined;
    return message;
  },
};

function createBaseTrades(): Trades {
  return { Trades: [] };
}

export const Trades = {
  encode(message: Trades, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.Trades) {
      Trade.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Trades {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTrades();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Trades.push(Trade.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Trades {
    return { Trades: globalThis.Array.isArray(object?.Trades) ? object.Trades.map((e: any) => Trade.fromJSON(e)) : [] };
  },

  toJSON(message: Trades): unknown {
    const obj: any = {};
    if (message.Trades?.length) {
      obj.Trades = message.Trades.map((e) => Trade.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Trades>, I>>(base?: I): Trades {
    return Trades.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Trades>, I>>(object: I): Trades {
    const message = createBaseTrades();
    message.Trades = object.Trades?.map((e) => Trade.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
