// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: trade-grpc.proto

package trade

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Ability to get all trade history views using the filter options
type Filter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationID string                 `protobuf:"bytes,10,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`
	From           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=From,proto3,oneof" json:"From,omitempty"`
	To             *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=To,proto3,oneof" json:"To,omitempty"`
	UserID         *string                `protobuf:"bytes,11,opt,name=UserID,proto3,oneof" json:"UserID,omitempty"`   // User ID for the trade
	OrderID        *string                `protobuf:"bytes,12,opt,name=OrderID,proto3,oneof" json:"OrderID,omitempty"` // Internal Order ID
	Limit          *int32                 `protobuf:"varint,14,opt,name=Limit,proto3,oneof" json:"Limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_trade_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_trade_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_trade_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *Filter) GetOrganizationID() string {
	if x != nil {
		return x.OrganizationID
	}
	return ""
}

func (x *Filter) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Filter) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Filter) GetUserID() string {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return ""
}

func (x *Filter) GetOrderID() string {
	if x != nil && x.OrderID != nil {
		return *x.OrderID
	}
	return ""
}

func (x *Filter) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type TradeKey struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExecutionID    string                 `protobuf:"bytes,1,opt,name=ExecutionID,proto3" json:"ExecutionID,omitempty"`
	OrganizationID string                 `protobuf:"bytes,2,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TradeKey) Reset() {
	*x = TradeKey{}
	mi := &file_trade_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeKey) ProtoMessage() {}

func (x *TradeKey) ProtoReflect() protoreflect.Message {
	mi := &file_trade_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeKey.ProtoReflect.Descriptor instead.
func (*TradeKey) Descriptor() ([]byte, []int) {
	return file_trade_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *TradeKey) GetExecutionID() string {
	if x != nil {
		return x.ExecutionID
	}
	return ""
}

func (x *TradeKey) GetOrganizationID() string {
	if x != nil {
		return x.OrganizationID
	}
	return ""
}

var File_trade_grpc_proto protoreflect.FileDescriptor

const file_trade_grpc_proto_rawDesc = "" +
	"\n" +
	"\x10trade-grpc.proto\x12\x05trade\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\vtrade.proto\"\x9e\x02\n" +
	"\x06Filter\x12&\n" +
	"\x0eOrganizationID\x18\n" +
	" \x01(\tR\x0eOrganizationID\x123\n" +
	"\x04From\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x04From\x88\x01\x01\x12/\n" +
	"\x02To\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x02To\x88\x01\x01\x12\x1b\n" +
	"\x06UserID\x18\v \x01(\tH\x02R\x06UserID\x88\x01\x01\x12\x1d\n" +
	"\aOrderID\x18\f \x01(\tH\x03R\aOrderID\x88\x01\x01\x12\x19\n" +
	"\x05Limit\x18\x0e \x01(\x05H\x04R\x05Limit\x88\x01\x01B\a\n" +
	"\x05_FromB\x05\n" +
	"\x03_ToB\t\n" +
	"\a_UserIDB\n" +
	"\n" +
	"\b_OrderIDB\b\n" +
	"\x06_Limit\"T\n" +
	"\bTradeKey\x12 \n" +
	"\vExecutionID\x18\x01 \x01(\tR\vExecutionID\x12&\n" +
	"\x0eOrganizationID\x18\x02 \x01(\tR\x0eOrganizationID2\x90\x01\n" +
	"\fTradeService\x12&\n" +
	"\x03Get\x12\x0f.trade.TradeKey\x1a\f.trade.Trade\"\x00\x120\n" +
	"\x06Upsert\x12\f.trade.Trade\x1a\x16.google.protobuf.Empty\"\x00\x12&\n" +
	"\x04List\x12\r.trade.Filter\x1a\r.trade.Trades\"\x00B/Z-github.com/sologenic/com-fs-trade-model;tradeb\x06proto3"

var (
	file_trade_grpc_proto_rawDescOnce sync.Once
	file_trade_grpc_proto_rawDescData []byte
)

func file_trade_grpc_proto_rawDescGZIP() []byte {
	file_trade_grpc_proto_rawDescOnce.Do(func() {
		file_trade_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trade_grpc_proto_rawDesc), len(file_trade_grpc_proto_rawDesc)))
	})
	return file_trade_grpc_proto_rawDescData
}

var file_trade_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_trade_grpc_proto_goTypes = []any{
	(*Filter)(nil),                // 0: trade.Filter
	(*TradeKey)(nil),              // 1: trade.TradeKey
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*Trade)(nil),                 // 3: trade.Trade
	(*emptypb.Empty)(nil),         // 4: google.protobuf.Empty
	(*Trades)(nil),                // 5: trade.Trades
}
var file_trade_grpc_proto_depIdxs = []int32{
	2, // 0: trade.Filter.From:type_name -> google.protobuf.Timestamp
	2, // 1: trade.Filter.To:type_name -> google.protobuf.Timestamp
	1, // 2: trade.TradeService.Get:input_type -> trade.TradeKey
	3, // 3: trade.TradeService.Upsert:input_type -> trade.Trade
	0, // 4: trade.TradeService.List:input_type -> trade.Filter
	3, // 5: trade.TradeService.Get:output_type -> trade.Trade
	4, // 6: trade.TradeService.Upsert:output_type -> google.protobuf.Empty
	5, // 7: trade.TradeService.List:output_type -> trade.Trades
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_trade_grpc_proto_init() }
func file_trade_grpc_proto_init() {
	if File_trade_grpc_proto != nil {
		return
	}
	file_trade_proto_init()
	file_trade_grpc_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trade_grpc_proto_rawDesc), len(file_trade_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trade_grpc_proto_goTypes,
		DependencyIndexes: file_trade_grpc_proto_depIdxs,
		MessageInfos:      file_trade_grpc_proto_msgTypes,
	}.Build()
	File_trade_grpc_proto = out.File
	file_trade_grpc_proto_goTypes = nil
	file_trade_grpc_proto_depIdxs = nil
}
