// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v6.30.2
// source: sologenic/com-fs-order-model/util.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import {
  ProcessState,
  processStateFromJSON,
  processStateToJSON,
} from "../com-fs-utils-lib/models/order-properties/order-properties";

export const protobufPackage = "order";

export interface LockLogRecord {
  Key: string;
  MustHaveState: ProcessState[];
  TargetState: ProcessState;
}

/**
 * The `Key` field represents the datastore key for the `Order` message.
 * The `KeyPrefix` field is used to create a key for broker or smart contract logs (prefix + key = key for logs).
 * The `IsNew` field identifies if the record linked to the key is new. This is helpful for recovery because
 * both the rescanner and the recovery service might pick up the same record. When creating log records, if `IsNew` is true, the Key is sent
 * through the channel for processing. Otherwise, it isn't sent, as an existing key signals the recovery service will handle it.
 */
export interface Key {
  Key: string;
  KeyPrefix?: string | undefined;
  IsNew?: boolean | undefined;
}

export interface InstanceID {
  InstanceID: string;
}

function createBaseLockLogRecord(): LockLogRecord {
  return { Key: "", MustHaveState: [], TargetState: 0 };
}

export const LockLogRecord = {
  encode(message: LockLogRecord, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Key !== "") {
      writer.uint32(10).string(message.Key);
    }
    writer.uint32(18).fork();
    for (const v of message.MustHaveState) {
      writer.int32(v);
    }
    writer.ldelim();
    if (message.TargetState !== 0) {
      writer.uint32(24).int32(message.TargetState);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): LockLogRecord {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLockLogRecord();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Key = reader.string();
          continue;
        case 2:
          if (tag === 16) {
            message.MustHaveState.push(reader.int32() as any);

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.MustHaveState.push(reader.int32() as any);
            }

            continue;
          }

          break;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.TargetState = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LockLogRecord {
    return {
      Key: isSet(object.Key) ? globalThis.String(object.Key) : "",
      MustHaveState: globalThis.Array.isArray(object?.MustHaveState)
        ? object.MustHaveState.map((e: any) => processStateFromJSON(e))
        : [],
      TargetState: isSet(object.TargetState) ? processStateFromJSON(object.TargetState) : 0,
    };
  },

  toJSON(message: LockLogRecord): unknown {
    const obj: any = {};
    if (message.Key !== "") {
      obj.Key = message.Key;
    }
    if (message.MustHaveState?.length) {
      obj.MustHaveState = message.MustHaveState.map((e) => processStateToJSON(e));
    }
    if (message.TargetState !== 0) {
      obj.TargetState = processStateToJSON(message.TargetState);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LockLogRecord>, I>>(base?: I): LockLogRecord {
    return LockLogRecord.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LockLogRecord>, I>>(object: I): LockLogRecord {
    const message = createBaseLockLogRecord();
    message.Key = object.Key ?? "";
    message.MustHaveState = object.MustHaveState?.map((e) => e) || [];
    message.TargetState = object.TargetState ?? 0;
    return message;
  },
};

function createBaseKey(): Key {
  return { Key: "", KeyPrefix: undefined, IsNew: undefined };
}

export const Key = {
  encode(message: Key, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Key !== "") {
      writer.uint32(10).string(message.Key);
    }
    if (message.KeyPrefix !== undefined) {
      writer.uint32(18).string(message.KeyPrefix);
    }
    if (message.IsNew !== undefined) {
      writer.uint32(24).bool(message.IsNew);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Key {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKey();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Key = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.KeyPrefix = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.IsNew = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Key {
    return {
      Key: isSet(object.Key) ? globalThis.String(object.Key) : "",
      KeyPrefix: isSet(object.KeyPrefix) ? globalThis.String(object.KeyPrefix) : undefined,
      IsNew: isSet(object.IsNew) ? globalThis.Boolean(object.IsNew) : undefined,
    };
  },

  toJSON(message: Key): unknown {
    const obj: any = {};
    if (message.Key !== "") {
      obj.Key = message.Key;
    }
    if (message.KeyPrefix !== undefined) {
      obj.KeyPrefix = message.KeyPrefix;
    }
    if (message.IsNew !== undefined) {
      obj.IsNew = message.IsNew;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Key>, I>>(base?: I): Key {
    return Key.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Key>, I>>(object: I): Key {
    const message = createBaseKey();
    message.Key = object.Key ?? "";
    message.KeyPrefix = object.KeyPrefix ?? undefined;
    message.IsNew = object.IsNew ?? undefined;
    return message;
  },
};

function createBaseInstanceID(): InstanceID {
  return { InstanceID: "" };
}

export const InstanceID = {
  encode(message: InstanceID, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.InstanceID !== "") {
      writer.uint32(10).string(message.InstanceID);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): InstanceID {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInstanceID();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.InstanceID = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InstanceID {
    return { InstanceID: isSet(object.InstanceID) ? globalThis.String(object.InstanceID) : "" };
  },

  toJSON(message: InstanceID): unknown {
    const obj: any = {};
    if (message.InstanceID !== "") {
      obj.InstanceID = message.InstanceID;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InstanceID>, I>>(base?: I): InstanceID {
    return InstanceID.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InstanceID>, I>>(object: I): InstanceID {
    const message = createBaseInstanceID();
    message.InstanceID = object.InstanceID ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
