// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.1
// source: sologenic/com-fs-utils-lib/models/order-properties/order-properties.proto

/* eslint-disable */

export const protobufPackage = "orderproperties";

/** Side is order side. */
export enum Side {
  /** SIDE_UNSPECIFIED - SIDE_UNSPECIFIED reserves the default value, to protect against unexpected settings. */
  SIDE_UNSPECIFIED = 0,
  /** SIDE_BUY - SIDE_BUY means that the order is to buy base_denom quantity with the price. */
  SIDE_BUY = 1,
  /** SIDE_SELL - SIDE_SELL means that the order is to sell base_denom quantity with the price. */
  SIDE_SELL = 2,
  UNRECOGNIZED = -1,
}

export function sideFromJSON(object: any): Side {
  switch (object) {
    case 0:
    case "SIDE_UNSPECIFIED":
      return Side.SIDE_UNSPECIFIED;
    case 1:
    case "SIDE_BUY":
      return Side.SIDE_BUY;
    case 2:
    case "SIDE_SELL":
      return Side.SIDE_SELL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Side.UNRECOGNIZED;
  }
}

export function sideToJSON(object: Side): string {
  switch (object) {
    case Side.SIDE_UNSPECIFIED:
      return "SIDE_UNSPECIFIED";
    case Side.SIDE_BUY:
      return "SIDE_BUY";
    case Side.SIDE_SELL:
      return "SIDE_SELL";
    case Side.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}
